--------------------------------------------------------------------------------
--  DROP ALL TABLES, SEQUENCE AND TRIGGERS
--------------------------------------------------------------------------------
DROP TRIGGER WT_RESPONSE_PKTRIG;
DROP SEQUENCE WT_RESPONSE_PKSEQ;
DROP TABLE WT_RESPONSE;

DROP TRIGGER WT_REVIEW_COMMENT_PKTRIG;
DROP SEQUENCE WT_REVIEW_COMMENT_PKSEQ;
DROP TABLE WT_REVIEW_COMMENT;

--------------------------------------------------------------------------------
--  DDL for Table WT_REVIEW_COMMENT
--------------------------------------------------------------------------------
CREATE TABLE WT_REVIEW_COMMENT (
  WT_REVIEW_COMMENT_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_TRANS_ID REFERENCES WT_TRANS(WT_TRANS_ID)
  ,WT_CHECKLIST_ID REFERENCES WT_CHECKLIST(WT_CHECKLIST_ID)   
  ,TRANS_TYPE VARCHAR2(32)
  ,FIELD_NAME VARCHAR2(32)
  ,WT_WELL_NUM VARCHAR2(24) 
  ,ISSUE_STATUS VARCHAR2(64)
  ,REVIEWER_COMMENTS CLOB
  ,CREATED_BY_ID NUMBER(*,0) 
  ,CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
  ,UPDATED_BY_ID NUMBER(*,0) 
  ,UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE SEQUENCE WT_REVIEW_COMMENT_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_REVIEW_COMMENT_PKTRIG
BEFORE INSERT
ON WT_REVIEW_COMMENT
FOR EACH ROW
BEGIN
  IF :NEW.WT_REVIEW_COMMENT_ID IS NULL THEN
    SELECT WT_REVIEW_COMMENT_PKSEQ.NEXTVAL INTO :NEW.WT_REVIEW_COMMENT_ID FROM DUAL;
  END IF;
END WT_REVIEW_COMMENT;
/

--------------------------------------------------------------------------------
--  DDL for Table WT_RESPONSE
--------------------------------------------------------------------------------
CREATE TABLE WT_RESPONSE (
  WT_RESPONSE_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_REVIEW_COMMENT_ID REFERENCES WT_REVIEW_COMMENT(WT_REVIEW_COMMENT_ID)
  ,RESPONSE_BY VARCHAR2(64)
  ,RESPONSE_COMMENTS CLOB
  ,CREATED_BY_ID NUMBER(*,0) 
  ,CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
  ,UPDATED_BY_ID NUMBER(*,0) 
  ,UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE SEQUENCE WT_RESPONSE_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_RESPONSE_PKTRIG
BEFORE INSERT
ON WT_RESPONSE
FOR EACH ROW
BEGIN
  IF :NEW.WT_RESPONSE_ID IS NULL THEN
    SELECT WT_RESPONSE_PKSEQ.NEXTVAL INTO :NEW.WT_RESPONSE_ID FROM DUAL;
  END IF;
END WT_RESPONSE;
/






