ALTER TABLE WT_CONTACT ADD IS_ACTIVE NUMBER(1,0) DEFAULT 1;

ALTER TABLE WT_GROUNDWATER RENAME COLUMN TOTAL_PUMPLING TO TOTAL_PUMPING; 
ALTER TABLE WT_GROUNDWATER RENAME COLUMN BASE_PUMPLING TO BASE_PUMPING;
ALTER TABLE WT_GROUNDWATER RENAME COLUMN CROSS_TRANS_PUMPLING TO CROSS_TRANS_PUMPING;

ALTER TABLE WT_ATTACHMENT ADD ATTACHMENT_TYPE VARCHAR2(64);
ALTER TABLE WT_ATTACHMENT ADD TITLE VARCHAR2(128);
ALTER TABLE WT_ATTACHMENT ADD CREATED_BY_ID NUMBER(*,0);
ALTER TABLE WT_ATTACHMENT ADD UPDATED_BY_ID NUMBER(*,0);

COMMIT;
