--------------------------------------------------------------------------------
--  Create Procedure to reset Sequence
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE reset_seq_to (p_Name IN VARCHAR2,
                                          p_val IN NUMBER)
IS
  v_num  NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'SELECT ' || p_Name || '.NEXTVAL FROM DUAL' INTO v_num;
  
  EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || p_Name || ' INCREMENT BY ' || (p_val - v_num - 1) ||'  MINVALUE 1';
  
  EXECUTE IMMEDIATE 'SELECT ' || p_Name ||'.NEXTVAL FROM DUAL' INTO v_num;
  
  EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || p_Name || ' INCREMENT BY 1 ';
  
  DBMS_OUTPUT.Put_Line('Sequence ' || p_Name ||' IS NOW AT ' || p_val);
END;
/


--------------------------------------------------------------------------------
--  Clean Account Tables
--------------------------------------------------------------------------------
SELECT * FROM APP_USER WHERE USERNAME IN('seller','reviewer','manager','admin');
SELECT * FROM APP_USER WHERE USERNAME NOT IN('seller','reviewer','manager','admin');

TRUNCATE TABLE USER_GROUP;
TRUNCATE TABLE USER_REGISTRATION;
select USER_REGISTER_PKSEQ.nextval from dual;
EXEC reset_seq('USER_REGISTER_PKSEQ');

DELETE FROM APP_USER WHERE USERNAME NOT IN('seller','reviewer','manager','admin');

--------------------------------------------------------------------------------
--  Clean Agency and related Tables
--------------------------------------------------------------------------------
select wt_agency_pkseq.nextval from dual;
SELECT * FROM WT_AGENCY WHERE WT_AGENCY_ID > 87;
DELETE FROM WT_AGENCY WHERE WT_AGENCY_ID > 87;
EXEC reset_seq_to('WT_AGENCY_PKSEQ', 88);

DELETE FROM WT_AGENCY_APPROVAL;
EXEC reset_seq('WT_AGENCY_APPROVAL_PKSEQ');
DELETE FROM WT_APP_AGENCY;

SELECT * FROM WT_BUYER WHERE WT_TRANS_ID > 152;
DELETE FROM WT_BUYER WHERE WT_TRANS_ID > 152;
TRUNCATE TABLE WT_BUYERS_CONTACT;

TRUNCATE TABLE WT_CHANGE_LOG;
EXEC reset_seq('WT_CHANGE_LOG_PKSEQ');
TRUNCATE TABLE WT_CONTACT;
EXEC reset_seq('WT_CONTACT_PKSEQ');

SELECT * FROM WT_SELLER WHERE WT_TRANS_ID > 152;
DELETE FROM WT_SELLER WHERE WT_TRANS_ID > 152;

--------------------------------------------------------------------------------
--  Clean Attachment and related Tables
--------------------------------------------------------------------------------
TRUNCATE TABLE WT_ATT_CHECKLIST;

DELETE FROM WT_TRANS_ATTACHMENTS WHERE WT_ATTACHMENT_ID > 350;
DELETE FROM WT_GW_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;
DELETE FROM WT_CI_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;
DELETE FROM WT_CI_MAP_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;
DELETE FROM WT_RV_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;
DELETE FROM WT_WELL_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;

DELETE FROM WT_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;
EXEC reset_seq_to('WT_ATTACHMENT_PKSEQ', 345);

DELETE FROM WT_TRACK_FILE;
EXEC reset_seq('WT_TRACK_FILE_PKSEQ');


--------------------------------------------------------------------------------
--  Clean Trans and related Tables
--------------------------------------------------------------------------------
UPDATE WT_CROP_IDLING SET WT_TRANS_ID=null;
TRUNCATE TABLE WT_CROP_IDLING;
EXEC reset_seq('WT_CROP_IDLING_PKSEQ');

DELETE FROM WT_GW_WELL;
DELETE FROM WT_GW_MONTHLY;
EXEC reset_seq('WT_GW_MONTHLY_PKSEQ');
UPDATE WT_GROUNDWATER SET WT_TRANS_ID=null;
DELETE FROM WT_GROUNDWATER;

DELETE FROM WT_LOCATION;
EXEC reset_seq('WT_LOCATION_PKSEQ');

DELETE FROM WT_PRE_TRANSFER;
EXEC reset_seq('WT_PRE_TRANSFER_PKSEQ');

DELETE FROM WT_RV_TARSTOR;
DELETE FROM WT_RESERVOIR;
EXEC reset_seq('WT_RESERVOIR_PKSEQ');

DELETE FROM WT_RESPONSE;
DELETE FROM WT_REVIEW_COMMENT;
DELETE FROM WT_REVIEWER_COMMENTS;
DELETE FROM WT_STATUS_TRACK;
EXEC reset_seq('WT_STATUS_TRACK_PKSEQ');

DELETE FROM WT_TRANS_CEQA;
DELETE FROM WT_TRANS_COUNTY;
DELETE FROM WT_TRANS_NEPA;
DELETE FROM WT_TRANS_REACH;
DELETE FROM WT_TRANS_SWRCB;
DELETE FROM WT_TRANS_REPORT;
DELETE FROM WT_TRANS_TRACK;
DELETE FROM WT_TRANS_TYPE;
DELETE FROM WT_TRANS_USER;
DELETE FROM WT_WATER_LOSS;
DELETE FROM WT_WATER_RIGHTS;
DELETE FROM WT_WELL;

DELETE FROM WT_TRANS WHERE WT_TRANS_ID > 160;
EXEC reset_seq_to('WT_TRANS_PKSEQ', 160);

--------------------------------------------------------------------------------
--  Drop Unused Tables
--------------------------------------------------------------------------------
DROP TABLE WT_DIV_RIGHT;


--------------------------------------------------------------------------------
--  Reinsert Table WT_AGENCY
--------------------------------------------------------------------------------
UPDATE APP_USER SET WT_CONTACT_ID=null;
DELETE FROM WT_CONTACT;
DELETE FROM WT_BUYER;
DELETE FROM WT_SELLER;
DELETE FROM WT_AGENCY;
EXEC reset_seq('WT_AGENCY_PKSEQ');

-- QAQC Database
ALTER TABLE WT_CONTACT DROP CONSTRAINT SYS_C0036459;
ALTER TABLE WT_CONTACT DROP CONSTRAINT SYS_C0036460;
ALTER TABLE WT_CONTACT DROP CONSTRAINT SYS_C0036461;
ALTER TABLE WT_BUYER DROP CONSTRAINT SYS_C0036448;
ALTER TABLE WT_SELLER DROP CONSTRAINT SYS_C0036446;

-- QAQC Database
DELETE FROM WT_APP_AGENCY;
DELETE FROM WT_AGENCY;
EXEC reset_seq('WT_AGENCY_PKSEQ');

-- QAQC Database
UPDATE WT_CONTACT SET WT_AGENCY_ID=null;
ALTER TABLE WT_CONTACT ADD CONSTRAINT SYS_C0036459 FOREIGN KEY(WT_AGENCY_ID) REFERENCES WT_AGENCY(WT_AGENCY_ID); 
ALTER TABLE WT_CONTACT ADD CONSTRAINT SYS_C0036461 FOREIGN KEY(WT_STATE_ID) REFERENCES WT_STATE(WT_STATE_ID); 
ALTER TABLE WT_BUYER ADD CONSTRAINT SYS_C0036448 FOREIGN KEY(WT_AGENCY_ID) REFERENCES WT_AGENCY(WT_AGENCY_ID); 
DELETE FROM WT_SELLER;
ALTER TABLE WT_SELLER ADD CONSTRAINT SYS_C0036446 FOREIGN KEY(WT_AGENCY_ID) REFERENCES WT_AGENCY(WT_AGENCY_ID); 


-- QAQC Database
SELECT * FROM WT_CONTACT WHERE WT_CONTACT_ID != 361;
DELETE FROM WT_CONTACT WHERE WT_CONTACT_ID != 361;
DELETE FROM USER_REGISTRATION;
EXEC reset_seq('USER_REGISTER_PKSEQ');
DELETE FROM WT_BUYER;

DELETE FROM WT_AGENCY_APPROVAL;
DELETE FROM WT_ATT_CHECKLIST;
EXEC reset_seq_to('CHECKLIST_PKSEQ', 71);
DELETE FROM WT_ATTACHMENT WHERE WT_ATTACHMENT_ID > 350;
EXEC reset_seq_to('WT_ATTACHMENT_PKSEQ', 345);

DELETE FROM WT_CHANGE_LOG;
EXEC reset_seq('WT_CHANGE_LOG_PKSEQ');
DELETE FROM WT_CROP_IDLING;
EXEC reset_seq('WT_CROP_IDLING_PKSEQ');
DELETE FROM WT_GW_MONTHLY;
EXEC reset_seq('WT_GW_MONTHLY_PKSEQ');
DELETE FROM WT_GW_WELL;
EXEC reset_seq('WT_GW_WELL_PKSEQ');
DELETE FROM WT_GROUNDWATER;
EXEC reset_seq('WT_GROUNDWATER_PKSEQ');
DELETE FROM WT_LOCATION;
EXEC reset_seq('WT_LOCATION_PKSEQ');
DELETE FROM WT_PRE_TRANSFER;
EXEC reset_seq('WT_PRE_TRANSFER_PKSEQ');
DELETE FROM WT_RV_PURPOSE;
DELETE FROM WT_RV_TARSTOR;
DELETE FROM WT_RESERVOIR;
EXEC reset_seq('WT_RESERVOIR_PKSEQ');
DELETE FROM WT_RESPONSE;
EXEC reset_seq('WT_RESPONSE_PKSEQ');
DELETE FROM WT_REVIEW_COMMENT;
DELETE FROM WT_REVIEWER_COMMENTS;

DELETE FROM WT_TRANS WHERE CREATED_BY_ID = 263;
EXEC reset_seq_to('WT_CONTACT_PKSEQ', 2);

SELECT * FROM WT_TRANS WHERE CREATED_BY_ID = 61 ORDER BY WT_TRANS_ID;
SELECT * FROM WT_TRANS WHERE CREATED_BY_ID = 261 ORDER BY WT_TRANS_ID;

Insert into WT_CONTACT (WT_CONTACT_ID,WT_AGENCY_ID,TITLE,LAST_NAME,MIDDLE_NAME,FIRST_NAME,EMAIL,PHONE_TYPE,PHONE_NUMBER,ADDRESS1,ADDRESS2,WT_CITY_ID,WT_STATE_ID,ZIPCODE,CREATED_DATE,CREATED_BY_ID,UPDATED_BY_ID,UPDATED_DATE,IS_ACTIVE,CITY_NAME,IS_BUYERS_CONTACT) values (1,75,'State Water Contractor','Chapman',null,'Eric','eChapman@test.gov','Office','(916) 234-5555','345 Cherry Str.',null,null,null,'95810',to_timestamp('28-MAR-16 03.31.53.167000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,263,to_timestamp('28-MAR-16 03.31.53.168000000 PM','DD-MON-RR HH.MI.SSXFF AM'),1,'Davis',1);

-- Sequences Index Adjust
EXEC reset_seq_to('WT_CHECKLIST_PKSEQ', 71);
EXEC reset_seq_to('GROUP_PKSEQ', 6);
EXEC reset_seq_to('USER_PKSEQ', 5);
EXEC reset_seq('USER_REGISTER_PKSEQ');
EXEC reset_seq_to('WT_CONTACT_PKSEQ', 3);
EXEC reset_seq('WT_GROUNDWATER_PKSEQ');
EXEC reset_seq('WT_IDLE_PLAN_PKSEQ');
EXEC reset_seq('WT_RESPONSE_PKSEQ');
EXEC reset_seq('WT_REVIEW_COMMENT_PKSEQ');
EXEC reset_seq('WT_REVIEWER_COMMENTS_PKSEQ');
EXEC reset_seq('WT_RV_TARSTOR_PKSEQ');
EXEC reset_seq('WT_TRANS_CEQA_PKSEQ');
EXEC reset_seq('WT_TRANS_NEPA_PKSEQ');
EXEC reset_seq('WT_TRANS_REACH_PKSEQ');
EXEC reset_seq('WT_TRANS_SWRCB_PKSEQ');
EXEC reset_seq('WT_TRANS_TRACK_PKSEQ');
EXEC reset_seq('WT_WATER_LOSS_PKSEQ');
EXEC reset_seq('WT_WATER_RIGHTS_PKSEQ');
EXEC reset_seq('WT_WELL_PKSEQ');


