
--------------------------------------------------------------------------------
--  Insert for Table WT_CHECKLIST
--------------------------------------------------------------------------------

SELECT WT.* FROM WT_CHECKLIST WT WHERE CHECKLIST_FIELD='GW_ATTACHMENT' ORDER BY SORT_ORDER;

-- Insert GW_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Economic analysis of potential impacts to area from which water will be transferred (Water Code Section 1810(d))', 'CHECKBOX', 12);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Compliance with CEQA/SWRCB Approval', 'CHECKBOX', 13);
/

-- Insert CI_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Economic analysis of potential impacts to area from which water will be transferred (Water Code Section 1810(d))', 'CHECKBOX', 16);
/

-- Insert RV_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('RV_ATTACHMENT', 'Compliance with CEQA/SWRCB Approval', 'CHECKBOX', 6);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('RV_ATTACHMENT', 'Economic analysis of potential impacts to area from which water will be transferred (Water Code Section 1810(d))', 'CHECKBOX', 7);
/

-- Insert BI_ATTACHMENT Checklist
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Buyer/Seller Agreement', 'CHECKBOX', 1);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Historic Data', 'CHECKBOX', 2);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Location Information', 'CHECKBOX', 3);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Proposal Report', 'CHECKBOX', 4);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'SWRCB Order', 'CHECKBOX', 5);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'CEQA Documents', 'CHECKBOX', 6);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'NEPA Documents', 'CHECKBOX', 7);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Other', 'CHECKBOX', 8);
UPDATE WT_CHECKLIST SET SORT_ORDER=8 WHERE checklist_field='BI_ATTACHMENT' and name='Other';
/


