
--------------------------------------------------------------------------------
--  Insert for Table WT_REVIEW_COMMENT
--------------------------------------------------------------------------------

-- Insert Trans#225 GW#161 Checklist
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 121, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 122, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 123, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 124, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 125, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 126, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 127, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 128, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 129, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 130, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 131, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 132, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 133, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 134, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 135, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 136, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 137, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 138, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 139, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 140, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 141, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 142, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 143, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (225, 144, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
/

-- Insert Trans#225 GW#161 Checklist for QA DB
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 81, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 82, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 83, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 84, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 85, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 86, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 87, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 88, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 89, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 90, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 91, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 92, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 93, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 94, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 95, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 96, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 97, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 98, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 99, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 100, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 101, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 102, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 103, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO WT_REVIEW_COMMENT(WT_TRANS_ID,WT_CHECKLIST_ID,TRANS_TYPE,ISSUE_STATUS,CREATED_DATE,UPDATED_DATE) VALUES (263, 104, 'GW', 'NEW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
/















