--------------------------------------------------------------------------------
--  DDL for Table WT_TRANS_ATTACHMENT
--------------------------------------------------------------------------------
DROP TABLE WT_TRANS_REPORT;

CREATE TABLE WT_TRANS_REPORT (
  WT_TRANS_ID REFERENCES WT_TRANS(WT_TRANS_ID)
  ,WT_ATTACHMENT_ID REFERENCES WT_ATTACHMENT(WT_ATTACHMENT_ID) ON DELETE CASCADE
  ,UNIQUE(WT_TRANS_ID,WT_ATTACHMENT_ID)
);
/

--------------------------------------------------------------------------------
--  Insert for Table WT_CHECKLIST
--------------------------------------------------------------------------------

SELECT WT.* FROM WT_CHECKLIST WT WHERE CHECKLIST_FIELD='TR_ATTACHMENT' ORDER BY SORT_ORDER;

-- Insert PR_ATTACHMENT Checklist
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Water Transfer Tracking Report', 'CHECKBOX', 1);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Water Transfer Monitoring Report', 'CHECKBOX', 2);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Water Transfer Process Report', 'CHECKBOX', 3);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Water Transfer Failure Report', 'CHECKBOX', 4);

--UPDATE WT_CHECKLIST SET NAME='Crop Idling Comments Box' WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND SORT_ORDER=1;
--UPDATE WT_CHECKLIST SET NAME='Crop Idling Field visit reports' WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND SORT_ORDER=2;
--UPDATE WT_CHECKLIST SET NAME='Crop Idling Water Purchase Program Results' WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND SORT_ORDER=3;
--UPDATE WT_CHECKLIST SET NAME='Draft Map of landowner and acres' WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND SORT_ORDER=4;

INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Crop Idling Comments Box', 'CHECKBOX', 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Crop Idling Field visit reports', 'CHECKBOX', 2);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Crop Idling Water Purchase Program Results', 'CHECKBOX', 3);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Draft Map of landowner and acres', 'CHECKBOX', 4);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Excessive Vegetation Documentation', 'CHECKBOX', 5);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Final Map of landowners and acres', 'CHECKBOX', 6);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Growers Sign-Up List', 'CHECKBOX', 7);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Monitoring Photographs', 'CHECKBOX', 8);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Verification of Idled Acreage', 'CHECKBOX', 9);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Groundwater Comments Box', 'CHECKBOX', 10);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Groundwater field visit reports', 'CHECKBOX', 11);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Groundwater monitoring records (where DWR monitoring wells are used)', 'CHECKBOX', 12);

-- Insert RV_ATTACHMENT Checklist
SELECT WT.* FROM WT_CHECKLIST WT WHERE CHECKLIST_FIELD='RV_ATTACHMENT' ORDER BY SORT_ORDER;

INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('RV_ATTACHMENT', 'Comments Box', 'CHECKBOX', 8);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('RV_ATTACHMENT', 'Daily record release', 'CHECKBOX', 9);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('RV_ATTACHMENT', 'Daily Reservoir storage', 'CHECKBOX', 10);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('RV_ATTACHMENT', 'Refill accounting spreadsheet', 'CHECKBOX', 11);

-- Insert GW_ATTACHMENT Checklist
SELECT WT.* FROM WT_CHECKLIST WT WHERE CHECKLIST_FIELD='GW_ATTACHMENT' ORDER BY SORT_ORDER;

INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Comments Box', 'CHECKBOX', 14);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Final Report', 'CHECKBOX', 15);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Groundwater Level', 'CHECKBOX', 16);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Land Subsidence measurements', 'CHECKBOX', 17);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Power Consumption in kilowatt-hours on a monthly basis', 'CHECKBOX', 18);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Record instantaneous and cumulative flow meter values (Groundwater Data Collection) in a spreadsheet. File name Month-Day-Year (Ex. 6-6-16.xlsx)', 'CHECKBOX', 19);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Water Quality', 'CHECKBOX', 20);
/










