
--------------------------------------------------------------------------------
--  Insert for Table WT_CHECKLIST
--------------------------------------------------------------------------------
--
select WT_CHECKLIST_PKSEQ.nextval from WT_CHECKLIST;
SELECT * FROM WT_CHECKLIST;
TRUNCATE TABLE WT_ATT_CHECKLIST; 
DELETE FROM WT_CHECKLIST;
--TRUNCATE TABLE WT_CHECKLIST;

SET DEFINE OFF;
BEGIN
  reset_seq('WT_CHECKLIST_PKSEQ');
END;
/

-- Insert WELL_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Well Completion Report', 'CHECKBOX', 1, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Well Construction', 'CHECKBOX', 2, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Geologic Log', 'CHECKBOX', 3, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Photo(s) of well site', 'CHECKBOX', 4, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Photo of meter', 'CHECKBOX', 5, 1, 0);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Meter Certification', 'CHECKBOX', 6, 1, 0);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Other', 'CHECKBOX', 7, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'March Readings', 'CHECKBOX', 8, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Monitoring Network', 'CHECKBOX', 9, 0, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Meter readings', 'CHECKBOX', 10, 1, 0);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Groundwater level measurements', 'CHECKBOX', 11, 1, 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Groundwater quality monitoring', 'CHECKBOX', 12, 1, 0);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER,WELL_TRANSFER,WELL_MONITORING) VALUES ('WELL_ATTACHMENT', 'Data evaluation and reporting', 'CHECKBOX', 13, 1, 1);

-- Insert GW_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Baseline Information', 'CHECKBOX', 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Historic Operations', 'CHECKBOX', 2);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Justification of a non 13% Depletion Factor', 'CHECKBOX', 3);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Schedule and volume of water to be pumped', 'CHECKBOX', 4);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Other', 'CHECKBOX', 5);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Land subsidence methods', 'CHECKBOX', 6);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Coordination plan', 'CHECKBOX', 7);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Data evaluation and reporting plan', 'CHECKBOX', 8);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Procedure to receive reports of effects', 'CHECKBOX', 9);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Procedure for investigating effects', 'CHECKBOX', 10);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Mitigation Plan and Financial Assurance Plan', 'CHECKBOX', 11);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Mitigation options', 'CHECKBOX', 11);
--INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('GW_ATTACHMENT', 'Financial assurances', 'CHECKBOX', 12);


--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (15, 'GW_ATTACHMENT', 'Baseline Information', 'CHECKBOX');
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (16, 'GW_ATTACHMENT', 'Historic Operations', 'CHECKBOX', 2);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (17, 'GW_ATTACHMENT', 'Justification of a non 12% Depletion Factor', 'CHECKBOX', 3);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (18, 'GW_ATTACHMENT', 'Schedule and volume of water to be pumped', 'CHECKBOX', 4);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (19, 'GW_ATTACHMENT', 'Other', 'CHECKBOX', 5);

--SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='BI_ATTACHMENT';
--DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='BI_ATTACHMENT';
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (15, 'BI_ATTACHMENT', 'Buyer/Seller Agreement', 'CHECKBOX', 1);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (16, 'BI_ATTACHMENT', 'Historic Data', 'CHECKBOX', 2);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (17, 'BI_ATTACHMENT', 'Location Information', 'CHECKBOX', 3);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (18, 'BI_ATTACHMENT', 'Proposal Report', 'CHECKBOX', 4);
--INSERT INTO WT_CHECKLIST(WT_CHECKLIST_ID,CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES (19, 'BI_ATTACHMENT', 'Other', 'CHECKBOX', 5);

-- Insert BI_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Buyer/Seller Agreement', 'CHECKBOX', 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Historic Data', 'CHECKBOX', 2);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Location Information', 'CHECKBOX', 3);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Proposal Report', 'CHECKBOX', 4);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('BI_ATTACHMENT', 'Other', 'CHECKBOX', 5);

-- Delete CI_ATTACHMENT Checklist
--DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='CI_ATTACHMENT';
-- Insert CI_ATTACHMENT Checklist
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Field Data Entry Form', 'CHECKBOX', 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Compliance with CEQA/SWRCB Approval', 'CHECKBOX', 2);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Mitigation Plan', 'CHECKBOX', 3);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of agency boundary', 'CHECKBOX', 4);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of field boundaries', 'CHECKBOX', 5);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of field identification numbers', 'CHECKBOX', 6);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of fields to be idled as part of water transfer', 'CHECKBOX', 7);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of fields to have crop shift as part of water transfer', 'CHECKBOX', 8);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of current year FSA acreage of each field', 'CHECKBOX', 9);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of areas known to have high seepage', 'CHECKBOX', 10);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of areas adjacent to wildlife refuges or areas managed for habitat', 'CHECKBOX', 11);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of portion of any fields dedicated to non-cropping purposes such as equipment storage', 'CHECKBOX', 12);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of fields currently irrigated', 'CHECKBOX', 13);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of fields routinely irrigated', 'CHECKBOX', 14);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('CI_ATTACHMENT', 'Map of fields routinely not irrigated', 'CHECKBOX', 15);
/






















