--------------------------------------------------------------------------------
--  Modify Table WT_TRANS
--------------------------------------------------------------------------------
ALTER TABLE WT_TRANS ADD PRO_TRANS_QUA_TMP NUMBER(18,2);
UPDATE WT_TRANS SET PRO_TRANS_QUA_TMP = PRO_TRANS_QUA;
/
UPDATE WT_TRANS SET PRO_TRANS_QUA=null;
ALTER TABLE WT_TRANS MODIFY PRO_TRANS_QUA NUMBER(18,2);
/
UPDATE WT_TRANS SET PRO_TRANS_QUA = PRO_TRANS_QUA_TMP;
UPDATE WT_TRANS SET PRO_TRANS_QUA_TMP=null;
ALTER TABLE WT_TRANS DROP COLUMN PRO_TRANS_QUA_TMP;
/

--------------------------------------------------------------------------------
--  Modify Table WT_TRANS_TYPE
--------------------------------------------------------------------------------
ALTER TABLE WT_TRANS_TYPE MODIFY TYPE_VOLUME NUMBER(18,2);

--------------------------------------------------------------------------------
--  Modify Table WT_WATER_RIGHTS
--------------------------------------------------------------------------------
ALTER TABLE WT_WATER_RIGHTS MODIFY PROPOSED_TRANS_VOL NUMBER(18,2);

--------------------------------------------------------------------------------
--  Modify table WT_CROP_IDLING
--------------------------------------------------------------------------------
UPDATE WT_CROP_IDLING SET WATER_TRANS_QUA=null;
ALTER TABLE WT_CROP_IDLING MODIFY WATER_TRANS_QUA NUMBER(18,2);
/

ALTER TABLE WT_CROP_IDLING DROP COLUMN WATER_RIGHT_ID;
ALTER TABLE WT_CROP_IDLING DROP COLUMN WATER_RIGHT_DESC;
ALTER TABLE WT_CROP_IDLING DROP COLUMN GROWER_NUM;
ALTER TABLE WT_CROP_IDLING DROP COLUMN CI_NAME;
/

--------------------------------------------------------------------------------
--  Modify table table WT_RESERVOIR
--------------------------------------------------------------------------------
UPDATE WT_RESERVOIR SET WATER_TRANS_QUA=null;
UPDATE WT_RESERVOIR SET TOP_ALLOW_STORAGE=null;
UPDATE WT_RESERVOIR SET TARGET_STORAGE=null;
UPDATE WT_RESERVOIR SET ACT_STORAGE=null;
UPDATE WT_RESERVOIR SET RES_DOWNSTREAM=null;
UPDATE WT_RESERVOIR SET PROPOSED_VOL=null;
UPDATE WT_RESERVOIR SET RES_AREA_CAPACITY=null;

ALTER TABLE WT_RESERVOIR MODIFY WATER_TRANS_QUA NUMBER(18,2);
ALTER TABLE WT_RESERVOIR MODIFY TOP_ALLOW_STORAGE NUMBER(18,2);
ALTER TABLE WT_RESERVOIR MODIFY TARGET_STORAGE NUMBER(18,2);
ALTER TABLE WT_RESERVOIR MODIFY ACT_STORAGE NUMBER(18,2);
ALTER TABLE WT_RESERVOIR MODIFY RES_DOWNSTREAM NUMBER(18,2);
ALTER TABLE WT_RESERVOIR MODIFY PROPOSED_VOL NUMBER(18,2);
ALTER TABLE WT_RESERVOIR MODIFY RES_AREA_CAPACITY NUMBER(18,2);
/

ALTER TABLE WT_RESERVOIR DROP COLUMN WATER_RIGHT_ID;
ALTER TABLE WT_RESERVOIR DROP COLUMN WATER_RIGHT_DESC;
/
--------------------------------------------------------------------------------
--  Modify table table WT_GROUNDWATER
--------------------------------------------------------------------------------
UPDATE WT_GROUNDWATER SET TOTAL_PUMPING=null;
UPDATE WT_GROUNDWATER SET BASE_PUMPING=null;
UPDATE WT_GROUNDWATER SET GROSS_TRANS_PUMPING=null;
UPDATE WT_GROUNDWATER SET NET_TRANS_WATER=null;

ALTER TABLE WT_GROUNDWATER MODIFY TOTAL_PUMPING NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER MODIFY BASE_PUMPING NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER MODIFY GROSS_TRANS_PUMPING NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER MODIFY NET_TRANS_WATER NUMBER(18,2);
/

ALTER TABLE WT_GROUNDWATER DROP COLUMN WATER_RIGHT_ID;
ALTER TABLE WT_GROUNDWATER DROP COLUMN WATER_RIGHT_DESC;
ALTER TABLE WT_GROUNDWATER ADD STREAM_DEPLETION NUMBER(18,2);
/

ALTER TABLE WT_GROUNDWATER MODIFY DEPLETION_FACTOR NUMBER(6,2);
/
--------------------------------------------------------------------------------
--  Modify table table WT_GW_MONTHLY
--------------------------------------------------------------------------------
UPDATE WT_GW_MONTHLY SET PROPOSED_PUMPING=null;
UPDATE WT_GW_MONTHLY SET BASELINE_PUMPING=null;
UPDATE WT_GW_MONTHLY SET GROSS_TRANS_PUMPING=null;
UPDATE WT_GW_MONTHLY SET STREAM_DEPLETION=null;
UPDATE WT_GW_MONTHLY SET NET_TRANS_WATER=null;

ALTER TABLE WT_GW_MONTHLY MODIFY PROPOSED_PUMPING NUMBER(18,2);
ALTER TABLE WT_GW_MONTHLY MODIFY BASELINE_PUMPING NUMBER(18,2);
ALTER TABLE WT_GW_MONTHLY MODIFY GROSS_TRANS_PUMPING NUMBER(18,2);
ALTER TABLE WT_GW_MONTHLY MODIFY STREAM_DEPLETION NUMBER(18,2);
ALTER TABLE WT_GW_MONTHLY MODIFY NET_TRANS_WATER NUMBER(18,2);
/


--------------------------------------------------------------------------------
--  Modify table table WT_WELL
--------------------------------------------------------------------------------
ALTER TABLE WT_WELL ADD SERIAL_NUM VARCHAR2(16);
/





