--------------------------------------------------------------------------------
--  Modify Table WT_STATUS_FLAG
--------------------------------------------------------------------------------

SELECT * FROM WT_STATUS_FLAG;
ALTER TABLE WT_TRANS DROP CONSTRAINT SYS_C0014414;
-- QA Database
ALTER TABLE WT_TRANS DROP CONSTRAINT SYS_C0023363;

DELETE FROM WT_STATUS_FLAG;

REM INSERTING into WT_STATUS_FLAG
SET DEFINE OFF;
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (0,'DRAFT','Saved proposal as draft');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (1,'SUBMITTED','Proposal submitted to DWR');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (2,'REVIEW','During DWR reviewing process');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (3,'SUSPEND','Proposal is suspend');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (4,'APPROVED','Proposal is approved');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (5,'TRACKING','During DWR track water transfer');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (6,'COMPLETE','Proposal is complete');
/

ALTER TABLE WT_TRANS ADD CONSTRAINT SYS_C0014414 FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID); 
-- QA Database
ALTER TABLE WT_TRANS ADD CONSTRAINT SYS_C0023363 FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID); 
--ALTER TABLE WT_TRANS ADD CONSTRAINT TRANS_STATUS FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID);

--------------------------------------------------------------------------------
--  Update Status for Table WT_TRANS
--------------------------------------------------------------------------------
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 0 WHERE WT_STATUS_FLAG_ID < 9;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE WT_STATUS_FLAG_ID = 9;




