
--------------------------------------------------------------------------------
--  Add Columns to Table WT_TRANS
--------------------------------------------------------------------------------

ALTER TABLE WT_TRANS ADD REQ_EXP_WIN VARCHAR2(64);
ALTER TABLE WT_TRANS ADD DESCRIPTION VARCHAR2(250) 
--ALTER TABLE WT_TRANS ADD SUBMITTED_DATE DATE;
--ALTER TABLE WT_TRANS ADD RECEIVED_DATE DATE;
/

-- Data fix for table WT_TRANS
SELECT * FROM WT_AGENCY WHERE AGENCY_CODE IN('BVWSD','WKWD');
INSERT INTO WT_SELLER("WT_TRANS_ID","WT_AGENCY_ID") VALUES ('5','8');
INSERT INTO WT_SELLER("WT_TRANS_ID","WT_AGENCY_ID") VALUES ('5','85');
--------------------------------------------------------------------------------
--  Modify Table WT_STATUS_FLAG
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--  Modify Table WT_STATUS_FLAG
--------------------------------------------------------------------------------

SELECT * FROM WT_STATUS_FLAG;
ALTER TABLE WT_TRANS DROP CONSTRAINT SYS_C0014414;
-- QA Database
--ALTER TABLE WT_TRANS DROP CONSTRAINT SYS_C0023363;

DELETE FROM WT_STATUS_FLAG;

REM INSERTING into WT_STATUS_FLAG
SET DEFINE OFF;
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (0,'DRAFT','Saved proposal as draft');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (1,'SUBMITTED','Proposal submitted to DWR');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (2,'RECEIVED','DWR received proposal');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (3,'REVIEW','During DWR reviewing process');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (4,'EVALUATE','During DWR evaluation process');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (5,'REJECT','Proposal is rejected');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (6,'COMPLETE','Proposal is complete');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (7,'APPROVED','Proposal is approved');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (8,'TRACK','During DWR track water transfer');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (9,'DONE','All process done and finished');
/

ALTER TABLE WT_TRANS ADD CONSTRAINT SYS_C0014414 FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID); 
-- QA Database
--ALTER TABLE WT_TRANS ADD CONSTRAINT SYS_C0023363 FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID); 
-- Modify WT_STATUS_FLAG_ID
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID=9 WHERE WT_STATUS_FLAG_ID=7;
-- QA Database
--UPDATE WT_TRANS SET WT_STATUS_FLAG_ID=9 WHERE WT_STATUS_FLAG_ID is NULL;

--------------------------------------------------------------------------------
--  DDL for Table WT_STATUS_TRACK
--------------------------------------------------------------------------------
DROP TRIGGER WT_STATUS_TRACK_PKTRIG;
DROP SEQUENCE WT_STATUS_TRACK_PKSEQ;
DROP TABLE WT_STATUS_TRACK;

CREATE TABLE WT_STATUS_TRACK (
  WT_STATUS_TRACK_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_TRANS_ID NUMERIC(16,0)
  ,STATUS_NAME VARCHAR2(16)  
  ,SUB_STATUS  VARCHAR2(128)
  ,STATUS_COMMENTS  VARCHAR2(256)
  ,USERNAME VARCHAR2(16)
  ,STATUS_DATE Date
);
/

CREATE SEQUENCE WT_STATUS_TRACK_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_STATUS_TRACK_PKTRIG
BEFORE INSERT
ON WT_STATUS_TRACK
FOR EACH ROW
BEGIN
  IF :NEW.WT_STATUS_TRACK_ID IS NULL THEN
    SELECT WT_STATUS_TRACK_PKSEQ.NEXTVAL
    INTO :NEW.WT_STATUS_TRACK_ID
    FROM DUAL;
  END IF;
  SELECT SYSTIMESTAMP INTO :NEW.STATUS_DATE FROM DUAL;
END WT_STATUS_TRACK;
/



