--------------------------------------------------------------------------------
--  DROP ALL TABLES AND SEQUENCE
--------------------------------------------------------------------------------
DROP TRIGGER WT_REVIEW_NOTE_PKTRIG;
DROP SEQUENCE WT_REVIEW_NOTE_PKSEQ;
DROP TABLE WT_REVIEW_NOTE;

DROP TRIGGER WT_INTERNAL_NOTE_PKTRIG;
DROP SEQUENCE WT_INTERNAL_NOTE_PKSEQ;
DROP TABLE WT_INTERNAL_NOTE;

--------------------------------------------------------------------------------
--  DDL for Table WT_REVIEW_NOTE
--------------------------------------------------------------------------------
CREATE TABLE WT_REVIEW_NOTE(
  WT_REVIEW_NOTE_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_TRANS_ID REFERENCES WT_TRANS(WT_TRANS_ID)
  ,SECTION_KEY VARCHAR2(16)
  ,IS_COMPLETE NUMBER(1,0) DEFAULT 0
  ,STATUS_KEY VARCHAR2(16)
  ,STATUS_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP
  ,STATUS_UPDATED_BY NUMBER(10,0)
  ,NOTE CLOB  
  ,NOTE_UPDATED_BY NUMBER(10,0)
  ,NOTE_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);
/

CREATE SEQUENCE WT_REVIEW_NOTE_PKSEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER WT_REVIEW_NOTE_PKTRIG
BEFORE INSERT
ON WT_REVIEW_NOTE
FOR EACH ROW
BEGIN
  IF :NEW.WT_REVIEW_NOTE_ID IS NULL THEN
    SELECT WT_REVIEW_NOTE_PKSEQ.NEXTVAL INTO :NEW.WT_REVIEW_NOTE_ID FROM DUAL;
  END IF;
  SELECT SYSTIMESTAMP INTO :NEW.STATUS_DATE FROM DUAL;
  SELECT SYSTIMESTAMP INTO :NEW.NOTE_DATE FROM DUAL;
END WT_REVIEW_NOTE;
/

--------------------------------------------------------------------------------
--  DDL for Table WT_INTERNAL_NOTE
--------------------------------------------------------------------------------
CREATE TABLE WT_INTERNAL_NOTE(
  WT_INTERNAL_NOTE_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_TRANS_ID REFERENCES WT_TRANS(WT_TRANS_ID)
  ,SECTION_KEY VARCHAR2(16)
  ,NOTE CLOB  
  ,NOTE_UPDATED_BY NUMBER(10,0)
  ,NOTE_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);
/

CREATE SEQUENCE WT_INTERNAL_NOTE_PKSEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER WT_INTERNAL_NOTE_PKTRIG
BEFORE INSERT
ON WT_INTERNAL_NOTE
FOR EACH ROW
BEGIN
  IF :NEW.WT_INTERNAL_NOTE_ID IS NULL THEN
    SELECT WT_INTERNAL_NOTE_PKSEQ.NEXTVAL INTO :NEW.WT_INTERNAL_NOTE_ID FROM DUAL;
  END IF;
  SELECT SYSTIMESTAMP INTO :NEW.NOTE_DATE FROM DUAL;
END WT_INTERNAL_NOTE;
/








