--------------------------------------------------------------------------------
--  Modify Table WT_STATUS_FLAG
--------------------------------------------------------------------------------

SELECT * FROM WT_STATUS_FLAG;
-- Local Databse
ALTER TABLE WT_TRANS DROP CONSTRAINT SYS_C0014414;
-- QA Database
ALTER TABLE WT_TRANS DROP CONSTRAINT SYS_C0023363;

DELETE FROM WT_STATUS_FLAG;

REM INSERTING into WT_STATUS_FLAG
SET DEFINE OFF;
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (0,'DRAFT','Draft');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (1,'SUBMITTED','Submitted');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (2,'UREVIEW','Under Review');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (3,'PCOMPLETE','Proposal Complete');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (4,'CAPPROVAL','Conditional Approval');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (5,'PAPPROVED','Proposal Approved');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (6,'CEXECUTED','Contract Executed');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (7,'SUSPEND','Suspend');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (8,'CANCEL','Cancel');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (9,'TPROGRESS','Transfer in Progress');
Insert into WT_STATUS_FLAG (WT_STATUS_FLAG_ID,STATUS_NAME,STATUS_DESCRIPTION) values (10,'TCOMPLETE','Transfer Completed');
/

-- Local Databse
ALTER TABLE WT_TRANS ADD CONSTRAINT SYS_C0014414 FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID); 
-- QAQC Database
ALTER TABLE WT_TRANS ADD CONSTRAINT SYS_C0023363 FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID); 
--ALTER TABLE WT_TRANS ADD CONSTRAINT TRANS_STATUS FOREIGN KEY(WT_STATUS_FLAG_ID) REFERENCES WT_STATUS_FLAG(WT_STATUS_FLAG_ID);

SELECT * FROM WT_TRANS WHERE WT_STATUS_FLAG_ID=9;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID=10 WHERE WT_STATUS_FLAG_ID=9;
SELECT * FROM WT_TRANS WHERE WT_STATUS_FLAG_ID=10;






