CREATE OR REPLACE VIEW WT_LIST_VIEW AS
SELECT
  t1.WT_TRANS_ID
  , t1.TRANS_YEAR 
  , t2.STATUS_NAME AS "STATUS"
  , t1.CREATE_DATE
  , t4.SELLER
  , t5.BUYERS
  , t1.WT_STATUS_FLAG_ID
  , t1.CREATED_BY_ID
  , t1.MODIFY_DATE
  , t1.IS_ACTIVE
  , t4.AGENCY_FULL_NAME
  , t1.PRO_ACR_IDLE_IND||t1.RES_RE_OP_IND||t1.WELL_USE_NUM_IND as TRANS_TYPE
from WT_TRANS t1
  join WT_STATUS_FLAG t2
  on t1.WT_STATUS_FLAG_ID = t2.WT_STATUS_FLAG_ID
  LEFT JOIN (SELECT t1.WT_TRANS_ID ,t3.AGENCY_FULL_NAME,
        TAB_TO_STRING(CAST(COLLECT(t3.AGENCY_CODE) AS T_VARCHAR2_TAB)) AS SELLER
      FROM WT_TRANS t1
        JOIN WT_SELLER t2
          JOIN WT_AGENCY t3
          ON t2.WT_AGENCY_ID = t3.WT_AGENCY_ID
        ON t1.WT_TRANS_ID = t2.WT_TRANS_ID  
      GROUP BY t1.WT_TRANS_ID,t3.AGENCY_FULL_NAME) t4
  ON t1.WT_TRANS_ID = t4.WT_TRANS_ID
  LEFT JOIN (SELECT t1.WT_TRANS_ID  ,
        TAB_TO_STRING(CAST(COLLECT(t3.AGENCY_CODE) AS T_VARCHAR2_TAB)) AS BUYERS
      FROM WT_TRANS t1
        JOIN WT_BUYER t2
          JOIN WT_AGENCY t3
          ON t2.WT_AGENCY_ID = t3.WT_AGENCY_ID
        ON t1.WT_TRANS_ID = t2.WT_TRANS_ID  
      GROUP BY t1.WT_TRANS_ID) t5
  ON t1.WT_TRANS_ID = t5.WT_TRANS_ID;


 
