SELECT WT_TRANS_ID, replace(PRO_ACR_IDLE_IND,1,'CI')||','||RES_RE_OP_IND||','||WELL_USE_NUM_IND as TRANS_TYPE FROM WT_TRANS ORDER BY WT_TRANS_ID;

SELECT WT_TRANS_ID, replace(replace(PRO_ACR_IDLE_IND,0,''), 1, 'CI ')||replace(replace(RES_RE_OP_IND,0,''), 1, 'RES ')||replace(replace(WELL_USE_NUM_IND,0,''), 1, 'GW ') as TRANS_TYPE FROM WT_TRANS ORDER BY WT_TRANS_ID;