CREATE TABLE WT_MESSAGE(
    MSG_ID      NUMERIC PRIMARY KEY,
    WT_TRANS_ID NUMBER(10,0),
    WT_CONTACT_ID  NUMBER(10,0),
	WT_AGENCY_ID NUMBER(10,0),
    CREATED_BY  NUMBER(10,0),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    MESSAGE VARCHAR2(4000 BYTE),
    SUBJECT VARCHAR2(100 BYTE)
);
/
CREATE SEQUENCE WT_MESSAGE_PKSEQ START WITH 1;
/
create or replace TRIGGER WT_MESSAGE_PKTRIG
BEFORE INSERT
ON WT_MESSAGE
FOR EACH ROW
BEGIN
  IF :NEW.MSG_ID IS NULL THEN
    SELECT WT_MESSAGE_PKSEQ.NEXTVAL
    INTO :NEW.MSG_ID
    FROM DUAL;
  END IF;
  SELECT SYSTIMESTAMP INTO :NEW.CREATED_DATE FROM DUAL;
END WT_MESSAGE;
/