--------------------------------------------------------
--  File created - Thursday-June-29-2017   
--------------------------------------------------------
DELETE FROM WT_COUNTY;

REM INSERTING into WT_COUNTY
SET DEFINE OFF;
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (1,'Alameda','ALA');
UPDATE WT_COUNTY SET NAME='Alameda', SHORT_NAME='ALA' WHERE WT_COUNTY_ID = 1;
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (2,'Alpine','ALP');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (3,'Amador','AMA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (4,'Butte','BUT');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (5,'Calaveras','CAL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (6,'Contra Costa','CCA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (7,'Colusa','COL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (8,'Del Norte','DEL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (9,'El Dorado','ELD');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (10,'Fresno','FRE');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (11,'Glenn','GLE');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (12,'Humboldt','HUM');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (13,'Imperial','IMP');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (14,'Inyo','INY');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (15,'Klamath','KLA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (16,'Kings','KNG');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (17,'Kern','KRN');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (18,'Lake','LAK');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (19,'Lassen','LAS');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (20,'Los Angeles','LAX');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (21,'Madera','MAD');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (22,'Mendocino','MEN');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (23,'Merced','MER');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (24,'Mono','MNO');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (25,'Monterey','MNT');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (26,'Modoc','MOD');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (27,'Mariposa','MPA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (28,'Marin','MRN');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (29,'Napa','NAP');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (30,'Nevada','NEV');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (31,'Orange','ORA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (32,'Placer','PLA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (33,'Plumas','PLU');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (34,'Riverside','RIV');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (35,'Sacramento','SAC');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (36,'Santa Barbara','SBA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (37,'San Bernardino','SBD');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (38,'San Benito','SBT');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (39,'Santa Clara','SCL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (40,'Santa Cruz','SCR');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (41,'San Diego','SDG');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (42,'San Francisco','SFO');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (43,'Shasta','SHA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (44,'Sierra','SIE');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (45,'Siskiyou','SIS');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (46,'San Joaquin','SJQ');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (47,'San Luis Obispo','SLO');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (48,'San Mateo','SMT');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (49,'Solano','SOL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (50,'Sonoma','SON');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (51,'Stanislaus','STA');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (52,'Sutter','SUT');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (53,'Tehama','TEH');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (54,'Trinity','TRI');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (55,'Tulare','TUL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (56,'Tuolumne','TUO');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (57,'Ventura','VEN');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (58,'Yolo','YOL');
Insert into WT_COUNTY (WT_COUNTY_ID,NAME,SHORT_NAME) values (59,'Yuba','YUB');
