--------------------------------------------------------------------------------
--  Modify Table WT_TRANS
--------------------------------------------------------------------------------
ALTER TABLE WT_TRANS ADD REQ_EXP_FROM_DATE DATE;
ALTER TABLE WT_TRANS ADD REQ_EXP_TO_DATE DATE;
ALTER TABLE WT_TRANS ADD CONTRACT_AMOUNT NUMBER(18,2);
ALTER TABLE WT_TRANS ADD CI_CONTRACT_AMOUNT NUMBER(18,2);
ALTER TABLE WT_TRANS ADD RV_CONTRACT_AMOUNT NUMBER(18,2);
ALTER TABLE WT_TRANS ADD GW_CONTRACT_AMOUNT NUMBER(18,2);

-- Not Run Yet, HOLD ON FOR CONFIRM
--ALTER TABLE WT_TRANS DROP COLUMN ACT_TRANS_QUA;
--ALTER TABLE WT_TRANS DROP COLUMN DWR_PRO_APPR_DATE;
--ALTER TABLE WT_TRANS DROP COLUMN PRO_AGREE_PAID;
--ALTER TABLE WT_TRANS DROP COLUMN ACT_AMT_PAID;
--ALTER TABLE WT_TRANS DROP COLUMN CAL_AMT_PAID;
--ALTER TABLE WT_TRANS DROP COLUMN PRO_UNIT_COST;
--ALTER TABLE WT_TRANS DROP COLUMN CAL_UNIT_COST;
--ALTER TABLE WT_TRANS DROP COLUMN PRO_ACR_IDLE;
--ALTER TABLE WT_TRANS DROP COLUMN ACT_FALL_ACR;
--ALTER TABLE WT_TRANS DROP COLUMN ACT_FALL_ACR_IND;
--ALTER TABLE WT_TRANS DROP COLUMN CONS_WATER_IND;
--ALTER TABLE WT_TRANS DROP COLUMN WELL_USE_NUM;
--ALTER TABLE WT_TRANS DROP COLUMN REQ_EXP_WIN;
--ALTER TABLE WT_TRANS DROP COLUMN DESCRIPTION;
--ALTER TABLE WT_TRANS DROP COLUMN PRO_RECEIVED_DATE;
--ALTER TABLE WT_TRANS DROP COLUMN SWRCB_APP;
--ALTER TABLE WT_TRANS DROP COLUMN WATER_AVL_TIMING;
--ALTER TABLE WT_TRANS DROP COLUMN DELTA_TRANSFER_IND;
--ALTER TABLE WT_TRANS DROP COLUMN DELTA_TRANSFER_COMM;
--ALTER TABLE WT_TRANS DROP COLUMN FISH_AGENCY_REVIEW;
--ALTER TABLE WT_TRANS DROP COLUMN POTENTIAL_AFFECT;
--ALTER TABLE WT_TRANS DROP COLUMN SWRCB_APP_PROCESS;
--ALTER TABLE WT_TRANS DROP COLUMN PROPOSAL_CATEGORY;
--ALTER TABLE WT_TRANS DROP COLUMN MAXIMUM_QUA;
--ALTER TABLE WT_TRANS DROP COLUMN SWRCB_APP_DATE;

SELECT * FROM WT_TRANS WHERE WT_STATUS_FLAG_ID = 10;
UPDATE WT_TRANS SET IS_ACTIVE = 0 WHERE WT_STATUS_FLAG_ID = 10;

--------------------------------------------------------------------------------
--  Modify Table WT_GROUNDWATER
--------------------------------------------------------------------------------
--ALTER TABLE WT_GROUNDWATER ADD APPROVED_WELLS_NUMBER NUMBER(8,0);


--------------------------------------------------------------------------------
--  DDL for Table WT_CI_MONTHLY
--------------------------------------------------------------------------------
DROP TRIGGER WT_CI_MONTHLY_PKTRIG;
DROP SEQUENCE WT_CI_MONTHLY_PKSEQ;
DROP TABLE WT_CI_MONTHLY;

CREATE TABLE WT_CI_MONTHLY (
  WT_CI_MONTHLY_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_CROP_IDLING_ID REFERENCES WT_CROP_IDLING(WT_CROP_IDLING_ID)
  ,MAY_ETAW NUMBER(2,0)
  ,MAY_TW NUMBER(18,2)
  ,JUNE_ETAW NUMBER(2,0)
  ,JUNE_TW NUMBER(18,2)
  ,JULY_ETAW NUMBER(2,0)
  ,JULY_TW NUMBER(18,2)
  ,AUGUST_ETAW NUMBER(2,0)
  ,AUGUST_TW NUMBER(18,2)
  ,SEPTEMBER_ETAW NUMBER(2,0)
  ,SEPTEMBER_TW NUMBER(18,2)
);
/

CREATE SEQUENCE WT_CI_MONTHLY_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_CI_MONTHLY_PKTRIG
BEFORE INSERT
ON WT_CI_MONTHLY
FOR EACH ROW
BEGIN
  IF :NEW.WT_CI_MONTHLY_ID IS NULL THEN
    SELECT WT_CI_MONTHLY_PKSEQ.NEXTVAL INTO :NEW.WT_CI_MONTHLY_ID FROM DUAL;
  END IF;
END WT_CI_MONTHLY;
/

--ALTER TABLE WT_CI_MONTHLY DROP COLUMN SEPTEMBER_WT;
--ALTER TABLE WT_CI_MONTHLY ADD SEPTEMBER_TW NUMBER(18,2);

--------------------------------------------------------------------------------
--  Modify Table WT_CROP_IDLING
--------------------------------------------------------------------------------
ALTER TABLE WT_CROP_IDLING ADD MAY_TW NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD JUNE_TW NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD JULY_TW NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD AUGUST_TW NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD SEPTEMBER_TW NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD ACTUAL_AMOUNT NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD CONTRACT_AMOUNT NUMBER(18,2);
ALTER TABLE WT_CROP_IDLING ADD DELIVERED_AMOUNT NUMBER(18,2);

--ALTER TABLE WT_CROP_IDLING DROP COLUMN MAY_WT;
--ALTER TABLE WT_CROP_IDLING DROP COLUMN JUNE_TW;
--ALTER TABLE WT_CROP_IDLING DROP COLUMN JULY_TW;
--ALTER TABLE WT_CROP_IDLING DROP COLUMN AUGUST_WT;
--ALTER TABLE WT_CROP_IDLING DROP COLUMN SEPTEMBER_WT;

ALTER TABLE WT_CROP_IDLING DROP COLUMN PRO_IDLE_ACR;
ALTER TABLE WT_CROP_IDLING DROP COLUMN ACT_FALL_ACR;
ALTER TABLE WT_CROP_IDLING DROP COLUMN IRRIGATED_ACR;
ALTER TABLE WT_CROP_IDLING DROP COLUMN DOUBLE_CROP_FALL_ACR;
/

--------------------------------------------------------------------------------
--  Modify Table WT_RESERVOIR
--------------------------------------------------------------------------------
ALTER TABLE WT_RESERVOIR ADD APRIL_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD MAY_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD JUNE_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD JULY_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD AUGUST_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD SEPTEMBER_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD OCTOBER_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD NOVEMBER_TW NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD ACTUAL_AMOUNT NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD CONTRACT_AMOUNT NUMBER(18,2);
ALTER TABLE WT_RESERVOIR ADD DELIVERED_AMOUNT NUMBER(18,2);

ALTER TABLE WT_RESERVOIR DROP COLUMN ACT_STORAGE;
ALTER TABLE WT_RESERVOIR DROP COLUMN RES_DOWNSTREAM;
ALTER TABLE WT_RESERVOIR DROP COLUMN PROPOSED_SCHEDULE;
ALTER TABLE WT_RESERVOIR DROP COLUMN PROPOSED_VOL;
ALTER TABLE WT_RESERVOIR DROP COLUMN RES_AREA_CAPACITY;
ALTER TABLE WT_RESERVOIR DROP COLUMN RIVER_MILE_START;
ALTER TABLE WT_RESERVOIR DROP COLUMN RIVER_MILE_END;
ALTER TABLE WT_RESERVOIR DROP COLUMN IS_OPR_OBLIGATION;
ALTER TABLE WT_RESERVOIR DROP COLUMN IS_REG_OBLIGATION;
ALTER TABLE WT_RESERVOIR DROP COLUMN IS_INSTREAM_REQ;

--------------------------------------------------------------------------------
--  Modify Table WT_GROUNDWATER
--------------------------------------------------------------------------------
ALTER TABLE WT_GROUNDWATER ADD APRIL_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD MAY_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD JUNE_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD JULY_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD AUGUST_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD SEPTEMBER_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD OCTOBER_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD NOVEMBER_TW NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD ACTUAL_AMOUNT NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD CONTRACT_AMOUNT NUMBER(18,2);
ALTER TABLE WT_GROUNDWATER ADD DELIVERED_AMOUNT NUMBER(18,2);

--------------------------------------------------------------------------------
--  Modify Table WT_CHECKLIST
--------------------------------------------------------------------------------
SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='CI_ATTACHMENT';
SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='CI_ATTACHMENT' AND NAME='Historic Data';
DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='CI_ATTACHMENT' AND NAME='Historic Data';

-- Delete Checklist for Reporting Attachment
SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT';

--SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Crop Idling Comments Box';
DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Crop Idling Comments Box';
--SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Draft Map of landowner and acres';
DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Draft Map of landowner and acres';
--SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Growers Sign-Up List';
DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Growers Sign-Up List';
--SELECT * FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Groundwater Comments Box';
DELETE FROM WT_CHECKLIST WHERE CHECKLIST_FIELD='TR_ATTACHMENT' AND NAME='Groundwater Comments Box';

INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('TR_ATTACHMENT', 'Executed Water Transfer Agreement', 'CHECKBOX', 13);

--------------------------------------------------------------------------------
--  Modify Table WT_FU_TYPE
--------------------------------------------------------------------------------
Insert into WT_FU_TYPE (WT_FU_TYPE_ID,FU_TYPE,FU_TYPE_DESCRIPTION,FU_SUB_TYPE) values (13,'CVP','Central Valley Project-Forbearance','Forbearance');
Insert into WT_FU_TYPE (WT_FU_TYPE_ID,FU_TYPE,FU_TYPE_DESCRIPTION,FU_SUB_TYPE) values (14,'CVP','Central Valley Project-Warren Act','Warren Act');


--------------------------------------------------------------------------------
--  Modify Table WT_WATER_LOSS
--------------------------------------------------------------------------------
ALTER TABLE WT_WATER_LOSS ADD REACH_LOSS_PERCENT NUMERIC(5,2);

--------------------------------------------------------------------------------
--  DDL for Table WT_CROP_TYPE
--------------------------------------------------------------------------------
DROP TRIGGER WT_CROP_TYPE_PKTRIG;
DROP SEQUENCE WT_CROP_TYPE_PKSEQ;
DROP TABLE WT_CROP_TYPE;

CREATE TABLE WT_CROP_TYPE (
  WT_CROP_TYPE_ID NUMERIC(16,0) PRIMARY KEY
  ,CROP_TYPE VARCHAR2(32 BYTE)
  ,CROP_ETAW NUMBER(4,2)
  ,CROP_DESCRIPTION VARCHAR2(256 BYTE)
);
/

CREATE SEQUENCE WT_CROP_TYPE_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_CROP_TYPE_PKTRIG
BEFORE INSERT
ON WT_CROP_TYPE
FOR EACH ROW
BEGIN
  IF :NEW.WT_CROP_TYPE_ID IS NULL THEN
    SELECT WT_CROP_TYPE_PKSEQ.NEXTVAL INTO :NEW.WT_CROP_TYPE_ID FROM DUAL;
  END IF;
END WT_CROP_TYPE;
/

--------------------------------------------------------------------------------
--  DDL for Table WT_CI_CROPTYPE
--------------------------------------------------------------------------------
DROP TRIGGER WT_CI_CROPTYPE_UPDATETRIG;
DROP TRIGGER WT_CI_CROPTYPE_PKTRIG;
DROP SEQUENCE WT_CI_CROPTYPE_PKSEQ;
DROP TABLE WT_CI_CROPTYPE;

CREATE TABLE WT_CI_CROPTYPE (
  WT_CI_CROPTYPE_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_CROP_IDLING_ID REFERENCES WT_CROP_IDLING(WT_CROP_IDLING_ID)
  ,CROP_TYPE VARCHAR2(32 BYTE)  
  ,PRO_TRANSFER_BY_CI NUMBER(18,2)
  ,PRO_TRANSFER_BY_CS NUMBER(18,2)
  ,PRO_TRANSFER_TOTAL NUMBER(18,2)
  ,CROP_ETAW NUMBER(4,2)
  ,WATER_TRANSFER_AMOUNT NUMBER(18,2)
  ,CREATED_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP
  ,CREATED_BY_ID NUMBER(*,0) 	
	,UPDATED_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP 
  ,UPDATED_BY_ID NUMBER(*,0)
);
/

CREATE SEQUENCE WT_CI_CROPTYPE_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_CI_CROPTYPE_PKTRIG
BEFORE INSERT
ON WT_CI_CROPTYPE
FOR EACH ROW
BEGIN
  IF :NEW.WT_CI_CROPTYPE_ID IS NULL THEN
    SELECT WT_CI_CROPTYPE_PKSEQ.NEXTVAL INTO :NEW.WT_CI_CROPTYPE_ID FROM DUAL;
  END IF;
  SELECT SYSTIMESTAMP INTO :NEW.CREATED_DATE FROM DUAL;
  SELECT SYSTIMESTAMP INTO :NEW.UPDATED_DATE FROM DUAL;
END WT_CI_CROPTYPE_PKTRIG;
/

CREATE OR REPLACE TRIGGER WT_CI_CROPTYPE_UPDATETRIG 
BEFORE UPDATE
ON WT_CI_CROPTYPE
FOR EACH ROW 
BEGIN 
  SELECT SYSTIMESTAMP INTO :NEW.UPDATED_DATE FROM DUAL; 
END WT_CI_CROPTYPE_UPDATETRIG;
/







