--------------------------------------------------------------------------------
--  Update Table WT_CHECKLIST
--------------------------------------------------------------------------------
UPDATE WT_CHECKLIST SET detail='Refer to Section 1.4 of the Water Transfer White Paper' WHERE WT_CHECKLIST_ID = 2;
UPDATE WT_CHECKLIST SET detail='Petition for Change with SWRCB (Refer to Section 1.5 of the Water Transfer White Paper)' WHERE WT_CHECKLIST_ID = 3;
UPDATE WT_CHECKLIST SET detail='Refer to Section 1.5 of the Water Transfer White Paper' WHERE WT_CHECKLIST_ID = 4;
UPDATE WT_CHECKLIST SET detail='Refer to Section 1.5 of the Water Transfer White Paper' WHERE WT_CHECKLIST_ID = 5;
UPDATE WT_CHECKLIST SET detail='Refer to Figure 1-1 of the Water Transfer White Paper' WHERE WT_CHECKLIST_ID = 6;

UPDATE WT_CHECKLIST SET detail='Provide records confirming compliance with local ordinances related to groundwater substitution water transfers, as described in Section 3-1 of the Water Transfer White Paper.' WHERE WT_CHECKLIST_ID = 36;
UPDATE WT_CHECKLIST SET detail='Provide the groundwater pumping, monitoring, and reporting plan. Plan should include a description of the monitoring well network, frequency of data collection and reporting for pumping, groundwater level, and groundwater quality measurements. Please refer to Section 3.5 of the Water Transfer White Paper for specific requirements.' WHERE WT_CHECKLIST_ID = 41;
UPDATE WT_CHECKLIST SET detail='Provide a mitigation plan as described in Section 3.6 of the Water Transfer White Paper.' WHERE WT_CHECKLIST_ID = 44;

--------------------------------------------------------------------------------
--  Update Table WT_AGENCY
--------------------------------------------------------------------------------
-- Delete Child first
SELECT * FROM WT_CONTACT WHERE WT_AGENCY_ID IN(101, 103);
DELETE FROM WT_CONTACT WHERE WT_AGENCY_ID IN(101, 103);

SELECT * FROM WT_AGENCY WHERE WT_AGENCY_ID IN(101, 103);
DELETE FROM WT_AGENCY WHERE WT_AGENCY_ID IN(101, 103);

UPDATE WT_AGENCY SET AGENCY_CODE = 'Zone 7', AGENCY_FULL_NAME = 'Alameda County Flood Control and Water Conservation District-Zone 7' WHERE WT_AGENCY_ID = 1;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Alameda', AGENCY_FULL_NAME = 'Alameda County Water District' WHERE WT_AGENCY_ID = 2;
UPDATE WT_AGENCY SET AGENCY_CODE = 'ACID', AGENCY_FULL_NAME = 'Anderson-Cottonwood Irrigation District' WHERE WT_AGENCY_ID = 3;
UPDATE WT_AGENCY SET AGENCY_CODE = 'AVEK', AGENCY_FULL_NAME = 'Antelope Valley-East Kern Water Agency' WHERE WT_AGENCY_ID = 4;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Avenal', AGENCY_FULL_NAME = 'Avenal State Prison' WHERE WT_AGENCY_ID = 5;
UPDATE WT_AGENCY SET AGENCY_CODE = 'BWGWD', AGENCY_FULL_NAME = 'Biggs-West Gridley Water District' WHERE WT_AGENCY_ID = 6;
UPDATE WT_AGENCY SET AGENCY_CODE = 'BVWSD ', AGENCY_FULL_NAME = 'Buena Vista Water Storage District' WHERE WT_AGENCY_ID = 7;
UPDATE WT_AGENCY SET AGENCY_CODE = 'BWD', AGENCY_FULL_NAME = 'Butte Water District' WHERE WT_AGENCY_ID = 9;
UPDATE WT_AGENCY SET AGENCY_CODE = 'BBID', AGENCY_FULL_NAME = 'Byron-Bethany Irrigation District' WHERE WT_AGENCY_ID = 10;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Conaway', AGENCY_FULL_NAME = 'Conaway Preservation Group, LLC' WHERE WT_AGENCY_ID = 11;
UPDATE WT_AGENCY SET AGENCY_CODE = 'CCWD', AGENCY_FULL_NAME = 'Contra Costa Water District' WHERE WT_AGENCY_ID = 12;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Cordua', AGENCY_FULL_NAME = 'Cordua Irrigation District' WHERE WT_AGENCY_ID = 15;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Kings', AGENCY_FULL_NAME = 'County of Kings' WHERE WT_AGENCY_ID = 16;
UPDATE WT_AGENCY SET AGENCY_CODE = 'DWR', AGENCY_FULL_NAME = 'Department of Water Resources' WHERE WT_AGENCY_ID = 17;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Desert', AGENCY_FULL_NAME = 'Desert Water Agency' WHERE WT_AGENCY_ID = 18;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Dry Creek', AGENCY_FULL_NAME = 'Dry Creek Mutual Water Company' WHERE WT_AGENCY_ID = 19;
UPDATE WT_AGENCY SET AGENCY_CODE = 'DRWD', AGENCY_FULL_NAME = 'Dudley Ridge Water District' WHERE WT_AGENCY_ID = 20;
UPDATE WT_AGENCY SET AGENCY_CODE = 'ECCID', AGENCY_FULL_NAME = 'East Contra Costa Irrigation District' WHERE WT_AGENCY_ID = 21;
UPDATE WT_AGENCY SET AGENCY_CODE = 'EMWC', AGENCY_FULL_NAME = 'East Side Mutual Water Company' WHERE WT_AGENCY_ID = 22;
UPDATE WT_AGENCY SET AGENCY_CODE = 'EID', AGENCY_FULL_NAME = 'El Dorado Irrigation District' WHERE WT_AGENCY_ID = 23;
UPDATE WT_AGENCY SET AGENCY_CODE = 'EWSID', AGENCY_FULL_NAME = 'Empire West Side Irrigation District' WHERE WT_AGENCY_ID = 24;
UPDATE WT_AGENCY SET AGENCY_CODE = 'FPUD', AGENCY_FULL_NAME = 'Foresthill Public Utility District' WHERE WT_AGENCY_ID = 25;
UPDATE WT_AGENCY SET AGENCY_CODE = 'FGSF', AGENCY_FULL_NAME = 'Frank Guisti and Son-Guisti Farms' WHERE WT_AGENCY_ID = 26;
UPDATE WT_AGENCY SET AGENCY_CODE = 'GHMWC', AGENCY_FULL_NAME = 'Garden Highway Mutual Water Company' WHERE WT_AGENCY_ID = 27;
UPDATE WT_AGENCY SET AGENCY_CODE = 'GCID', AGENCY_FULL_NAME = 'Glenn-Colusa Irrigation District' WHERE WT_AGENCY_ID = 28;
UPDATE WT_AGENCY SET AGENCY_CODE = 'GCF', AGENCY_FULL_NAME = 'Goose Club Farms' WHERE WT_AGENCY_ID = 29;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Hallwood', AGENCY_FULL_NAME = 'Hallwood Irrigation Company' WHERE WT_AGENCY_ID = 30;
UPDATE WT_AGENCY SET AGENCY_CODE = 'KCWA', AGENCY_FULL_NAME = 'Kern County Water Agency' WHERE WT_AGENCY_ID = 31;
UPDATE WT_AGENCY SET AGENCY_CODE = 'KTWD', AGENCY_FULL_NAME = 'Kern-Tulare Water District' WHERE WT_AGENCY_ID = 32;
UPDATE WT_AGENCY SET AGENCY_CODE = 'LCID', AGENCY_FULL_NAME = 'Littlerock Creek Irrigation District' WHERE WT_AGENCY_ID = 33;
UPDATE WT_AGENCY SET AGENCY_CODE = 'LTRID', AGENCY_FULL_NAME = 'Lower Tule River Irrigation District' WHERE WT_AGENCY_ID = 34;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Maxwell', AGENCY_FULL_NAME = 'Maxwell Irrigation District' WHERE WT_AGENCY_ID = 35;
UPDATE WT_AGENCY SET AGENCY_CODE = 'MID', AGENCY_FULL_NAME = 'Merced Irrigation District' WHERE WT_AGENCY_ID = 36;
UPDATE WT_AGENCY SET AGENCY_CODE = 'MFMWC', AGENCY_FULL_NAME = 'Meridian Farms Mutual Water Company' WHERE WT_AGENCY_ID = 37;
UPDATE WT_AGENCY SET AGENCY_CODE = 'MWD', AGENCY_FULL_NAME = 'The Metropolitan Water District of Southern California' WHERE WT_AGENCY_ID = 38;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Mojave', AGENCY_FULL_NAME = 'Mojave Water Agency' WHERE WT_AGENCY_ID = 39;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Napa', AGENCY_FULL_NAME = 'Napa County Flood Control and Water Conservation District' WHERE WT_AGENCY_ID = 40;
UPDATE WT_AGENCY SET AGENCY_CODE = 'NatomasWater', AGENCY_FULL_NAME = 'Natomas Central Mutual Water Company' WHERE WT_AGENCY_ID = 41;
UPDATE WT_AGENCY SET AGENCY_CODE = 'NCWD', AGENCY_FULL_NAME = 'Newhall County Water District' WHERE WT_AGENCY_ID = 42;
UPDATE WT_AGENCY SET AGENCY_CODE = 'OFWD', AGENCY_FULL_NAME = 'Oak Flat Water District' WHERE WT_AGENCY_ID = 43;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Palmdale', AGENCY_FULL_NAME = 'Palmdale Water District' WHERE WT_AGENCY_ID = 44;
UPDATE WT_AGENCY SET AGENCY_CODE = 'PMWC', AGENCY_FULL_NAME = 'Pelger Mutual Water Company' WHERE WT_AGENCY_ID = 45;
UPDATE WT_AGENCY SET AGENCY_CODE = 'PCWA', AGENCY_FULL_NAME = 'Placer County Water Agency' WHERE WT_AGENCY_ID = 46;
UPDATE WT_AGENCY SET AGENCY_CODE = 'PGMWC', AGENCY_FULL_NAME = 'Pleasant Grove-Verona Mutual Water Company' WHERE WT_AGENCY_ID = 47;
UPDATE WT_AGENCY SET AGENCY_CODE = 'PMWC', AGENCY_FULL_NAME = 'Plumas Mutual Water Company' WHERE WT_AGENCY_ID = 48;
UPDATE WT_AGENCY SET AGENCY_CODE = 'PCGID', AGENCY_FULL_NAME = 'Princeton-Cordora-Glenn Irrigation District' WHERE WT_AGENCY_ID = 49;
UPDATE WT_AGENCY SET AGENCY_CODE = 'PID', AGENCY_FULL_NAME = 'Provident Irrigation District' WHERE WT_AGENCY_ID = 50;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RGWD', AGENCY_FULL_NAME = 'Rag Gulch Water District' WHERE WT_AGENCY_ID = 51;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RWD', AGENCY_FULL_NAME = 'Ramirez Water District' WHERE WT_AGENCY_ID = 52;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RD1004', AGENCY_FULL_NAME = 'Reclamation District 1004' WHERE WT_AGENCY_ID = 53;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RD108', AGENCY_FULL_NAME = 'Reclamation District 108' WHERE WT_AGENCY_ID = 54;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RID', AGENCY_FULL_NAME = 'Richvale Irrigation District' WHERE WT_AGENCY_ID = 55;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RGF', AGENCY_FULL_NAME = 'River Garden Farms Company' WHERE WT_AGENCY_ID = 56;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RRBWSD', AGENCY_FULL_NAME = 'Rosedale-Rio Bravo Water Storage District' WHERE WT_AGENCY_ID = 57;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SGA', AGENCY_FULL_NAME = 'Sacramento Groundwater Authority' WHERE WT_AGENCY_ID = 58;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SRR', AGENCY_FULL_NAME = 'Sacramento River Ranch, LLC' WHERE WT_AGENCY_ID = 59;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SSWD', AGENCY_FULL_NAME = 'Sacramento Suburban Water District' WHERE WT_AGENCY_ID = 60;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SSWDN', AGENCY_FULL_NAME = 'Sacramento Suburban Water District North' WHERE WT_AGENCY_ID = 61;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SSWDS', AGENCY_FULL_NAME = 'Sacramento Suburban Water District South' WHERE WT_AGENCY_ID = 62;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SBVMWD', AGENCY_FULL_NAME = 'San Bernardino Valley Municipal Water District' WHERE WT_AGENCY_ID = 63;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SDCWA', AGENCY_FULL_NAME = 'San Diego County Water Authority' WHERE WT_AGENCY_ID = 64;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SJWD', AGENCY_FULL_NAME = 'San Juan Water District' WHERE WT_AGENCY_ID = 65;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SLDWA', AGENCY_FULL_NAME = 'San Luis and Delta-Mendota Water Authority' WHERE WT_AGENCY_ID = 66;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SLWD', AGENCY_FULL_NAME = 'San Luis Water District' WHERE WT_AGENCY_ID = 67;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Santa Barbara', AGENCY_FULL_NAME = 'Santa Barbara County Flood Control and Water Conservation District' WHERE WT_AGENCY_ID = 68;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Santa Clara', AGENCY_FULL_NAME = 'Santa Clara Valley Water District' WHERE WT_AGENCY_ID = 69;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Semitropic', AGENCY_FULL_NAME = 'Semitropic Water Storage District' WHERE WT_AGENCY_ID = 70;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SFWPA', AGENCY_FULL_NAME = 'South Feather Water and Power Agency' WHERE WT_AGENCY_ID = 71;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SSJID', AGENCY_FULL_NAME = 'South San Joaquin Irrigation District' WHERE WT_AGENCY_ID = 72;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SSWD', AGENCY_FULL_NAME = 'South Sutter Water District' WHERE WT_AGENCY_ID = 73;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SYWD', AGENCY_FULL_NAME = 'South Yuba Water District' WHERE WT_AGENCY_ID = 74;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SWP', AGENCY_FULL_NAME = 'State Water Project Contractors' WHERE WT_AGENCY_ID = 75;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SWD', AGENCY_FULL_NAME = 'Stevenson Water District' WHERE WT_AGENCY_ID = 76;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SEWD', AGENCY_FULL_NAME = 'Sutter Extension Water District' WHERE WT_AGENCY_ID = 77;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SMWC', AGENCY_FULL_NAME = 'Sutter Mutual Water Company' WHERE WT_AGENCY_ID = 78;
UPDATE WT_AGENCY SET AGENCY_CODE = 'TVT', AGENCY_FULL_NAME = 'Te Velde Trust' WHERE WT_AGENCY_ID = 79;
UPDATE WT_AGENCY SET AGENCY_CODE = 'TCCA', AGENCY_FULL_NAME = 'Tehama-Colusa Canal Authority' WHERE WT_AGENCY_ID = 80;
UPDATE WT_AGENCY SET AGENCY_CODE = 'TWSD', AGENCY_FULL_NAME = 'Thermalito Water and Sewer District' WHERE WT_AGENCY_ID = 81;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Tulare', AGENCY_FULL_NAME = 'Tulare Lake Basin Water Storage District' WHERE WT_AGENCY_ID = 82;
UPDATE WT_AGENCY SET AGENCY_CODE = 'TBF', AGENCY_FULL_NAME = 'Tule Basin Farms' WHERE WT_AGENCY_ID = 83;
UPDATE WT_AGENCY SET AGENCY_CODE = 'USBR', AGENCY_FULL_NAME = 'United States Bureau of Reclamation' WHERE WT_AGENCY_ID = 84;
UPDATE WT_AGENCY SET AGENCY_CODE = 'WHWD', AGENCY_FULL_NAME = 'West Hills Water District' WHERE WT_AGENCY_ID = 86;
UPDATE WT_AGENCY SET AGENCY_CODE = 'WKWD', AGENCY_FULL_NAME = 'West Kern Water District' WHERE WT_AGENCY_ID = 87;
UPDATE WT_AGENCY SET AGENCY_CODE = 'WCWD', AGENCY_FULL_NAME = 'Western Canal Water District' WHERE WT_AGENCY_ID = 88;
UPDATE WT_AGENCY SET AGENCY_CODE = 'WWD', AGENCY_FULL_NAME = 'Westlands Water District' WHERE WT_AGENCY_ID = 89;
UPDATE WT_AGENCY SET AGENCY_CODE = 'YCWA', AGENCY_FULL_NAME = 'Yuba County Water Agency' WHERE WT_AGENCY_ID = 90;
UPDATE WT_AGENCY SET AGENCY_CODE = 'RD2068', AGENCY_FULL_NAME = 'Reclamation District 2068' WHERE WT_AGENCY_ID = 102;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SWC', AGENCY_FULL_NAME = 'State Water Contractors' WHERE WT_AGENCY_ID = 121;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Solano', AGENCY_FULL_NAME = 'Solano County Water Agency' WHERE WT_AGENCY_ID = 141;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Castaic', AGENCY_FULL_NAME = 'Castaic Lake Water Agency' WHERE WT_AGENCY_ID = 161;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Yuba City', AGENCY_FULL_NAME = 'City of Yuba City' WHERE WT_AGENCY_ID = 162;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Coachella', AGENCY_FULL_NAME = 'Coachella Valley Water District' WHERE WT_AGENCY_ID = 163;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Butte', AGENCY_FULL_NAME = 'County of Butte' WHERE WT_AGENCY_ID = 164;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Crestline', AGENCY_FULL_NAME = 'Crestline-Lake Arrowhead Water Agency' WHERE WT_AGENCY_ID = 165;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Plumas', AGENCY_FULL_NAME = 'Plumas County Flood Control and Water Conservation District' WHERE WT_AGENCY_ID = 166;
UPDATE WT_AGENCY SET AGENCY_CODE = 'San Gabriel', AGENCY_FULL_NAME = 'San Gabriel Valley Municipal Water District' WHERE WT_AGENCY_ID = 167;
UPDATE WT_AGENCY SET AGENCY_CODE = 'San Gorgonio', AGENCY_FULL_NAME = 'San Gorgonio Pass Water Agency' WHERE WT_AGENCY_ID = 168;
UPDATE WT_AGENCY SET AGENCY_CODE = 'San Luis Obispo', AGENCY_FULL_NAME = 'San Luis Obispo County Flood Control and Water Conservation District' WHERE WT_AGENCY_ID = 169;
UPDATE WT_AGENCY SET AGENCY_CODE = 'Ventura', AGENCY_FULL_NAME = 'Ventura County Watershed Protection District' WHERE WT_AGENCY_ID = 170;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SJVNC', AGENCY_FULL_NAME = 'San Joaquin Valley National Cemetery' WHERE WT_AGENCY_ID = 171;
UPDATE WT_AGENCY SET AGENCY_CODE = 'SacCity', AGENCY_FULL_NAME = 'City of Sacramento' WHERE WT_AGENCY_ID = 172;


--------------------------------------------------------------------------------
--  Update Tables from DWR Spreadsheet
--------------------------------------------------------------------------------
-- Item# 17
SELECT * FROM WT_CROP_IDLING WHERE WT_TRANS_ID=1283;
UPDATE WT_CROP_IDLING SET TOTAL_TRANSFER_ACR=30000 WHERE WT_CROP_IDLING_ID=341;

-- Item# 16
SELECT * FROM WT_TRANS WHERE WT_TRANS_ID=1283;
UPDATE WT_TRANS SET PRO_TRANS_QUA=30000 WHERE WT_TRANS_ID=1283;

-- Item# 15
SELECT * FROM WT_RESERVOIR WHERE WT_TRANS_ID=1292;
--SELECT * FROM WT_GROUNDWATER WHERE WT_TRANS_ID=1292;
DELETE FROM WT_RESERVOIR WHERE WT_TRANS_ID=1292;

-- Item# 12/13/14 6/7/8
SELECT * FROM WT_GROUNDWATER WHERE WT_TRANS_ID=1316;
UPDATE WT_GROUNDWATER SET EXPORT_AMOUNT=34, EXPORTED_AMOUNT=27, DELIVERED_AMOUNT=27 WHERE WT_TRANS_ID=1316;
UPDATE WT_GROUNDWATER SET JULY_TW=11, AUGUST_TW=11, SEPTEMBER_TW=12 WHERE WT_TRANS_ID=1316;

-- Item# 9/10/11
SELECT * FROM WT_CROP_IDLING WHERE WT_TRANS_ID=1316;
UPDATE WT_CROP_IDLING SET EXPORT_AMOUNT=104, EXPORTED_AMOUNT=83, DELIVERED_AMOUNT=81 WHERE WT_TRANS_ID=1316;

-- Item# 5
SELECT * FROM WT_TRANS WHERE WT_TRANS_ID=1258;
UPDATE WT_TRANS SET PRO_TRANS_QUA=3090.56 WHERE WT_TRANS_ID=1258;

-- Item# 4
SELECT * FROM WT_TRANS WHERE WT_TRANS_ID=1262;
UPDATE WT_TRANS SET PRO_TRANS_QUA=4708 WHERE WT_TRANS_ID=1262;

-- Item# 5
SELECT * FROM WT_GROUNDWATER WHERE WT_TRANS_ID IN(1315,1316);
UPDATE WT_GROUNDWATER SET TOTAL_PUMPING=5071, BASE_PUMPING=0, NET_TRANS_WATER=4462.48, PUMPING_WELLS_NUMBER=2 WHERE WT_TRANS_ID=1316;
UPDATE WT_GROUNDWATER SET MONITORING_WELLS_NUMBER=12, DEPLETION_FACTOR=12, GROSS_TRANS_PUMPING=5071, STREAM_DEPLETION=608.52 WHERE WT_TRANS_ID=1316;

SELECT * FROM WT_GW_MONTHLY WHERE WT_GROUNDWATER_ID IN(344,362);
Insert into WT_GW_MONTHLY (WT_GROUNDWATER_ID,GW_MONTH,PROPOSED_PUMPING,BASELINE_PUMPING,STREAM_DEPLETION,NET_TRANS_WATER,GROSS_TRANS_PUMPING,MEASUREMENT_DATE) values (362,5,1027,0,123.24,903.76,1027,null);
Insert into WT_GW_MONTHLY (WT_GROUNDWATER_ID,GW_MONTH,PROPOSED_PUMPING,BASELINE_PUMPING,STREAM_DEPLETION,NET_TRANS_WATER,GROSS_TRANS_PUMPING,MEASUREMENT_DATE) values (362,6,995,0,119.4,875.6,995,null);
Insert into WT_GW_MONTHLY (WT_GROUNDWATER_ID,GW_MONTH,PROPOSED_PUMPING,BASELINE_PUMPING,STREAM_DEPLETION,NET_TRANS_WATER,GROSS_TRANS_PUMPING,MEASUREMENT_DATE) values (362,7,1027,0,123.24,903.76,1027,null);
Insert into WT_GW_MONTHLY (WT_GROUNDWATER_ID,GW_MONTH,PROPOSED_PUMPING,BASELINE_PUMPING,STREAM_DEPLETION,NET_TRANS_WATER,GROSS_TRANS_PUMPING,MEASUREMENT_DATE) values (362,8,1027,0,123.24,903.76,1027,null);
Insert into WT_GW_MONTHLY (WT_GROUNDWATER_ID,GW_MONTH,PROPOSED_PUMPING,BASELINE_PUMPING,STREAM_DEPLETION,NET_TRANS_WATER,GROSS_TRANS_PUMPING,MEASUREMENT_DATE) values (362,9,995,0,119.4,875.6,995,null);











