--------------------------------------------------------------------------------
--  Modify Table WT_TRANS Data
--------------------------------------------------------------------------------

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2015;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2015;

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2014 AND IS_ACTIVE = 1;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2014 AND IS_ACTIVE = 1;

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2013 AND IS_ACTIVE = 1;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2013 AND IS_ACTIVE = 1;

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2012 AND IS_ACTIVE = 1;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2012 AND IS_ACTIVE = 1;

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2011 AND IS_ACTIVE = 1;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2011 AND IS_ACTIVE = 1;

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2010 AND IS_ACTIVE = 1;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2010 AND IS_ACTIVE = 1;

SELECT WT_TRANS_ID, WT_STATUS_FLAG_ID FROM WT_TRANS WHERE TRANS_YEAR = 2009 AND IS_ACTIVE = 1;
UPDATE WT_TRANS SET WT_STATUS_FLAG_ID = 6 WHERE TRANS_YEAR = 2009 AND IS_ACTIVE = 1;

SELECT t.WT_TRANS_ID, t.TRANS_YEAR, a.AGENCY_FULL_NAME FROM WT_TRANS t, WT_SELLER s, WT_AGENCY a WHERE t.WT_TRANS_ID=s.WT_TRANS_ID AND s.WT_AGENCY_ID=a.WT_AGENCY_ID AND t.TRANS_YEAR = 2009 AND t.IS_ACTIVE = 1 ORDER BY t.WT_TRANS_ID;

Insert into WT_STATUS_TRACK (WT_TRANS_ID,STATUS_NAME,STATUS_DESCRIPTION,SUB_STATUS,STATUS_COMMENTS,USERNAME,STATUS_DATE,CREATED_BY_ID) values (1221,'SUBMITTED','Submitted',null,'System Record','Yu Mei',to_date('21-JUL-17','DD-MON-RR'),61);
Insert into WT_STATUS_TRACK (WT_TRANS_ID,STATUS_NAME,STATUS_DESCRIPTION,SUB_STATUS,STATUS_COMMENTS,USERNAME,STATUS_DATE,CREATED_BY_ID) values (1220,'SUBMITTED','Submitted',null,'System Record','Yu Mei',to_date('21-JUL-17','DD-MON-RR'),61);
Insert into WT_STATUS_TRACK (WT_TRANS_ID,STATUS_NAME,STATUS_DESCRIPTION,SUB_STATUS,STATUS_COMMENTS,USERNAME,STATUS_DATE,CREATED_BY_ID) values (1219,'SUBMITTED','Submitted',null,'System Record','Yu Mei',to_date('21-JUL-17','DD-MON-RR'),61);
Insert into WT_STATUS_TRACK (WT_TRANS_ID,STATUS_NAME,STATUS_DESCRIPTION,SUB_STATUS,STATUS_COMMENTS,USERNAME,STATUS_DATE,CREATED_BY_ID) values (1218,'SUBMITTED','Submitted',null,'System Record','Yu Mei',to_date('21-JUL-17','DD-MON-RR'),61);
Insert into WT_STATUS_TRACK (WT_TRANS_ID,STATUS_NAME,STATUS_DESCRIPTION,SUB_STATUS,STATUS_COMMENTS,USERNAME,STATUS_DATE,CREATED_BY_ID) values (1217,'SUBMITTED','Submitted',null,'System Record','Yu Mei',to_date('21-JUL-17','DD-MON-RR'),61);
Insert into WT_STATUS_TRACK (WT_TRANS_ID,STATUS_NAME,STATUS_DESCRIPTION,SUB_STATUS,STATUS_COMMENTS,USERNAME,STATUS_DATE,CREATED_BY_ID) values (1216,'SUBMITTED','Submitted',null,'System Record','Yu Mei',to_date('21-JUL-17','DD-MON-RR'),61);

SELECT WT_TRANS_ID,CONTRACT_AMOUNT,CI_CONTRACT_AMOUNT,RV_CONTRACT_AMOUNT,GW_CONTRACT_AMOUNT FROM WT_TRANS 
WHERE CI_CONTRACT_AMOUNT IS NOT NULL OR RV_CONTRACT_AMOUNT IS NOT NULL OR GW_CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;

SELECT WT_TRANS_ID,CI_CONTRACT_AMOUNT FROM WT_TRANS WHERE CI_CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;
SELECT WT_TRANS_ID,CONTRACT_AMOUNT FROM WT_CROP_IDLING WHERE WT_TRANS_ID IN(SELECT WT_TRANS_ID FROM WT_TRANS WHERE CI_CONTRACT_AMOUNT IS NOT NULL) ORDER BY WT_TRANS_ID;
SELECT t.WT_TRANS_ID, t.CI_CONTRACT_AMOUNT FROM WT_TRANS t, WT_CROP_IDLING c WHERE c.WT_TRANS_ID = t.WT_TRANS_ID;
SELECT WT_TRANS_ID,CONTRACT_AMOUNT FROM WT_CROP_IDLING ORDER BY WT_TRANS_ID;
UPDATE WT_CROP_IDLING c SET CONTRACT_AMOUNT = (SELECT t.CI_CONTRACT_AMOUNT FROM WT_TRANS t WHERE c.WT_TRANS_ID = t.WT_TRANS_ID);

SELECT WT_TRANS_ID,RV_CONTRACT_AMOUNT FROM WT_TRANS WHERE RV_CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;
SELECT WT_TRANS_ID,CONTRACT_AMOUNT FROM WT_RESERVOIR WHERE WT_TRANS_ID IN(SELECT WT_TRANS_ID FROM WT_TRANS WHERE RV_CONTRACT_AMOUNT IS NOT NULL) ORDER BY WT_TRANS_ID;
SELECT t.WT_TRANS_ID, t.RV_CONTRACT_AMOUNT FROM WT_TRANS t, WT_RESERVOIR r WHERE r.WT_TRANS_ID = t.WT_TRANS_ID;
SELECT WT_TRANS_ID,CONTRACT_AMOUNT FROM WT_RESERVOIR ORDER BY WT_TRANS_ID;
UPDATE WT_RESERVOIR r SET CONTRACT_AMOUNT = (SELECT t.RV_CONTRACT_AMOUNT FROM WT_TRANS t WHERE r.WT_TRANS_ID = t.WT_TRANS_ID);

SELECT WT_TRANS_ID,GW_CONTRACT_AMOUNT FROM WT_TRANS WHERE GW_CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;
SELECT WT_TRANS_ID,CONTRACT_AMOUNT FROM WT_GROUNDWATER WHERE WT_TRANS_ID IN(SELECT WT_TRANS_ID FROM WT_TRANS WHERE GW_CONTRACT_AMOUNT IS NOT NULL) ORDER BY WT_TRANS_ID;
SELECT t.WT_TRANS_ID, t.RV_CONTRACT_AMOUNT FROM WT_TRANS t, WT_GROUNDWATER g WHERE g.WT_TRANS_ID = t.WT_TRANS_ID;
SELECT WT_TRANS_ID,CONTRACT_AMOUNT FROM WT_GROUNDWATER ORDER BY WT_TRANS_ID;
UPDATE WT_GROUNDWATER g SET CONTRACT_AMOUNT = (SELECT t.GW_CONTRACT_AMOUNT FROM WT_TRANS t WHERE g.WT_TRANS_ID = t.WT_TRANS_ID);


SELECT WT_TRANS_ID, MAY_TW, JUNE_TW, JULY_TW, AUGUST_TW, SEPTEMBER_TW, CONTRACT_AMOUNT, ACTUAL_AMOUNT,
        COALESCE(MAY_TW,0)+COALESCE(JUNE_TW,0)+COALESCE(JULY_TW,0)+COALESCE(AUGUST_TW,0)+COALESCE(SEPTEMBER_TW,0) AS TOTAL 
        FROM WT_CROP_IDLING WHERE CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;
UPDATE WT_CROP_IDLING SET ACTUAL_AMOUNT = (COALESCE(MAY_TW,0)+COALESCE(JUNE_TW,0)+COALESCE(JULY_TW,0)+COALESCE(AUGUST_TW,0)+COALESCE(SEPTEMBER_TW,0)) WHERE CONTRACT_AMOUNT IS NOT NULL;


SELECT WT_TRANS_ID, MAY_TW, JUNE_TW, JULY_TW, AUGUST_TW, SEPTEMBER_TW, OCTOBER_TW, NOVEMBER_TW, CONTRACT_AMOUNT, ACTUAL_AMOUNT,
        COALESCE(MAY_TW,0)+COALESCE(JUNE_TW,0)+COALESCE(JULY_TW,0)+COALESCE(AUGUST_TW,0)+COALESCE(SEPTEMBER_TW,0)+COALESCE(OCTOBER_TW,0)+COALESCE(NOVEMBER_TW,0) AS TOTAL 
        FROM WT_RESERVOIR WHERE CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;
UPDATE WT_RESERVOIR SET ACTUAL_AMOUNT = COALESCE(MAY_TW,0)+COALESCE(JUNE_TW,0)+COALESCE(JULY_TW,0)+COALESCE(AUGUST_TW,0)+COALESCE(SEPTEMBER_TW,0)+COALESCE(OCTOBER_TW,0)+COALESCE(NOVEMBER_TW,0) WHERE CONTRACT_AMOUNT IS NOT NULL;


SELECT WT_TRANS_ID, MAY_TW, JUNE_TW, JULY_TW, AUGUST_TW, SEPTEMBER_TW, OCTOBER_TW, NOVEMBER_TW, CONTRACT_AMOUNT, ACTUAL_AMOUNT,
        COALESCE(MAY_TW,0)+COALESCE(JUNE_TW,0)+COALESCE(JULY_TW,0)+COALESCE(AUGUST_TW,0)+COALESCE(SEPTEMBER_TW,0)+COALESCE(OCTOBER_TW,0)+COALESCE(NOVEMBER_TW,0) AS TOTAL 
        FROM WT_GROUNDWATER WHERE CONTRACT_AMOUNT IS NOT NULL ORDER BY WT_TRANS_ID;
UPDATE WT_GROUNDWATER SET ACTUAL_AMOUNT = COALESCE(MAY_TW,0)+COALESCE(JUNE_TW,0)+COALESCE(JULY_TW,0)+COALESCE(AUGUST_TW,0)+COALESCE(SEPTEMBER_TW,0)+COALESCE(OCTOBER_TW,0)+COALESCE(NOVEMBER_TW,0) WHERE CONTRACT_AMOUNT IS NOT NULL;
        
        
--------------------------------------------------------------------------------
--  Modify Table WT_CHECKLIST Data
--------------------------------------------------------------------------------
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('PP_ATTACHMENT', 'Water Code Section 1810 Findings', 'CHECKBOX', 1);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('PP_ATTACHMENT', 'Notice of Intent to Adopt Negative Declaration', 'CHECKBOX', 2);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('PP_ATTACHMENT', 'Notice of Determination (NOD)', 'CHECKBOX', 3);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('PP_ATTACHMENT', 'Notice of Exemption (NOE)', 'CHECKBOX', 4);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('PP_ATTACHMENT', 'Notice of Completion & Environmental Document Transmittal', 'CHECKBOX', 5);
INSERT INTO WT_CHECKLIST(CHECKLIST_FIELD,NAME,CHECKLIST_TYPE,SORT_ORDER) VALUES ('PP_ATTACHMENT', 'Executed Water Transfer Agreement', 'CHECKBOX', 6);


--------------------------------------------------------------------------------
--  Check Table WT_WATER_LOSS Data
--------------------------------------------------------------------------------

SELECT * FROM WT_WATER_LOSS WHERE WT_TRANS_ID IN(1283, 1297, 1300, 1301, 1310, 1312, 1317, 1318, 1320);

SELECT * FROM WT_WATER_LOSS ORDER BY WT_TRANS_ID;

--------------------------------------------------------------------------------
--  Update Table WT_AGENCY Data
--------------------------------------------------------------------------------
SELECT * FROM WT_AGENCY WHERE WT_AGENCY_ID IN(7,8,11,12,13,14);
SELECT * FROM WT_AGENCY WHERE WT_AGENCY_ID IN(8,13,14);
DELETE FROM WT_AGENCY WHERE WT_AGENCY_ID IN(8,13,14);
DELETE FROM WT_AGENCY WHERE WT_AGENCY_ID = 8;
DELETE FROM WT_AGENCY WHERE WT_AGENCY_ID = 13;
DELETE FROM WT_AGENCY WHERE WT_AGENCY_ID = 14;

SELECT * FROM WT_BUYER WHERE WT_AGENCY_ID = 8;
SELECT * FROM WT_BUYER WHERE WT_AGENCY_ID = 11;
SELECT * FROM WT_BUYER WHERE WT_AGENCY_ID = 13;
UPDATE WT_BUYER SET WT_AGENCY_ID = 11 WHERE WT_AGENCY_ID = 13;

SELECT * FROM WT_BUYER WHERE WT_AGENCY_ID = 12;
SELECT * FROM WT_BUYER WHERE WT_AGENCY_ID = 14;
UPDATE WT_BUYER SET WT_AGENCY_ID = 12 WHERE WT_AGENCY_ID = 14;

SELECT * FROM WT_SELLER WHERE WT_AGENCY_ID = 7;
SELECT * FROM WT_SELLER WHERE WT_AGENCY_ID = 8;
UPDATE WT_SELLER SET WT_AGENCY_ID = 7 WHERE WT_AGENCY_ID = 8;

SELECT * FROM WT_SELLER WHERE WT_AGENCY_ID = 11;
SELECT * FROM WT_SELLER WHERE WT_AGENCY_ID = 13;
UPDATE WT_SELLER SET WT_AGENCY_ID = 11 WHERE WT_AGENCY_ID = 13;

SELECT * FROM WT_SELLER WHERE WT_AGENCY_ID = 12;
SELECT * FROM WT_SELLER WHERE WT_AGENCY_ID = 14;
UPDATE WT_SELLER SET WT_AGENCY_ID = 12 WHERE WT_AGENCY_ID = 14;

SELECT * FROM WT_CONTACT WHERE WT_AGENCY_ID = 11;
SELECT * FROM WT_CONTACT WHERE WT_AGENCY_ID = 13;
UPDATE WT_CONTACT SET WT_AGENCY_ID = 11 WHERE WT_AGENCY_ID = 13;

SELECT * FROM WT_CONTACT WHERE WT_AGENCY_ID = 12;
SELECT * FROM WT_CONTACT WHERE WT_AGENCY_ID = 14;
UPDATE WT_CONTACT SET WT_AGENCY_ID = 12 WHERE WT_AGENCY_ID = 14;









