--------------------------------------------------------
--  File created - Thursday-June-29-2017   
--------------------------------------------------------

UPDATE WT_COUNTY SET NAME='Alameda', SHORT_NAME='ALA' WHERE WT_COUNTY_ID = 1;
UPDATE WT_COUNTY SET NAME='Alpine', SHORT_NAME='ALP' WHERE WT_COUNTY_ID = 2;
UPDATE WT_COUNTY SET NAME='Amador', SHORT_NAME='AMA' WHERE WT_COUNTY_ID = 3;
UPDATE WT_COUNTY SET NAME='Butte', SHORT_NAME='BUT' WHERE WT_COUNTY_ID = 4;
UPDATE WT_COUNTY SET NAME='Calaveras', SHORT_NAME='CAL' WHERE WT_COUNTY_ID = 5;
UPDATE WT_COUNTY SET NAME='Contra Costa', SHORT_NAME='CCA' WHERE WT_COUNTY_ID = 6;
UPDATE WT_COUNTY SET NAME='Colusa', SHORT_NAME='COL' WHERE WT_COUNTY_ID = 7;
UPDATE WT_COUNTY SET NAME='Del Norte', SHORT_NAME='DEL' WHERE WT_COUNTY_ID = 8;
UPDATE WT_COUNTY SET NAME='El Dorado', SHORT_NAME='ELD' WHERE WT_COUNTY_ID = 9;
UPDATE WT_COUNTY SET NAME='Fresno', SHORT_NAME='FRE' WHERE WT_COUNTY_ID = 10;
UPDATE WT_COUNTY SET NAME='Glenn', SHORT_NAME='GLE' WHERE WT_COUNTY_ID = 11;
UPDATE WT_COUNTY SET NAME='Humboldt', SHORT_NAME='HUM' WHERE WT_COUNTY_ID = 12;
UPDATE WT_COUNTY SET NAME='Imperial', SHORT_NAME='IMP' WHERE WT_COUNTY_ID = 13;
UPDATE WT_COUNTY SET NAME='Inyo', SHORT_NAME='INY' WHERE WT_COUNTY_ID = 14;
UPDATE WT_COUNTY SET NAME='Klamath', SHORT_NAME='KLA' WHERE WT_COUNTY_ID = 15;
UPDATE WT_COUNTY SET NAME='Kings', SHORT_NAME='KNG' WHERE WT_COUNTY_ID = 16;
UPDATE WT_COUNTY SET NAME='Kern', SHORT_NAME='KRN' WHERE WT_COUNTY_ID = 17;
UPDATE WT_COUNTY SET NAME='Lake', SHORT_NAME='LAK' WHERE WT_COUNTY_ID = 18;
UPDATE WT_COUNTY SET NAME='Lassen', SHORT_NAME='LAS' WHERE WT_COUNTY_ID = 19;
UPDATE WT_COUNTY SET NAME='Los Angeles', SHORT_NAME='LAX' WHERE WT_COUNTY_ID = 20;
UPDATE WT_COUNTY SET NAME='Madera', SHORT_NAME='MAD' WHERE WT_COUNTY_ID = 21;
UPDATE WT_COUNTY SET NAME='Mendocino', SHORT_NAME='MEN' WHERE WT_COUNTY_ID = 22;
UPDATE WT_COUNTY SET NAME='Merced', SHORT_NAME='MER' WHERE WT_COUNTY_ID = 23;
UPDATE WT_COUNTY SET NAME='Mono', SHORT_NAME='MNO' WHERE WT_COUNTY_ID = 24;
UPDATE WT_COUNTY SET NAME='Monterey', SHORT_NAME='MNT' WHERE WT_COUNTY_ID = 25;
UPDATE WT_COUNTY SET NAME='Modoc', SHORT_NAME='MOD' WHERE WT_COUNTY_ID = 26;
UPDATE WT_COUNTY SET NAME='Mariposa', SHORT_NAME='MPA' WHERE WT_COUNTY_ID = 27;
UPDATE WT_COUNTY SET NAME='Marin', SHORT_NAME='MRN' WHERE WT_COUNTY_ID = 28;
UPDATE WT_COUNTY SET NAME='Napa', SHORT_NAME='NAP' WHERE WT_COUNTY_ID = 29;
UPDATE WT_COUNTY SET NAME='Nevada', SHORT_NAME='NEV' WHERE WT_COUNTY_ID = 30;
UPDATE WT_COUNTY SET NAME='Orange', SHORT_NAME='ORA' WHERE WT_COUNTY_ID = 31;
UPDATE WT_COUNTY SET NAME='Placer', SHORT_NAME='PLA' WHERE WT_COUNTY_ID = 32;
UPDATE WT_COUNTY SET NAME='Plumas', SHORT_NAME='PLU' WHERE WT_COUNTY_ID = 33;
UPDATE WT_COUNTY SET NAME='Riverside', SHORT_NAME='RIV' WHERE WT_COUNTY_ID = 34;
UPDATE WT_COUNTY SET NAME='Sacramento', SHORT_NAME='SAC' WHERE WT_COUNTY_ID = 35;
UPDATE WT_COUNTY SET NAME='Santa Barbara', SHORT_NAME='SBA' WHERE WT_COUNTY_ID = 36;
UPDATE WT_COUNTY SET NAME='San Bernardino', SHORT_NAME='SBD' WHERE WT_COUNTY_ID = 37;
UPDATE WT_COUNTY SET NAME='San Benito', SHORT_NAME='SBT' WHERE WT_COUNTY_ID = 38;
UPDATE WT_COUNTY SET NAME='Santa Clara', SHORT_NAME='SCL' WHERE WT_COUNTY_ID = 39;
UPDATE WT_COUNTY SET NAME='Santa Cruz', SHORT_NAME='SCR' WHERE WT_COUNTY_ID = 40;
UPDATE WT_COUNTY SET NAME='San Diego', SHORT_NAME='SDG' WHERE WT_COUNTY_ID = 41;
UPDATE WT_COUNTY SET NAME='San Francisco', SHORT_NAME='SFO' WHERE WT_COUNTY_ID = 42;
UPDATE WT_COUNTY SET NAME='Shasta', SHORT_NAME='SHA' WHERE WT_COUNTY_ID = 43;
UPDATE WT_COUNTY SET NAME='Sierra', SHORT_NAME='SIE' WHERE WT_COUNTY_ID = 44;
UPDATE WT_COUNTY SET NAME='Siskiyou', SHORT_NAME='SIS' WHERE WT_COUNTY_ID = 45;
UPDATE WT_COUNTY SET NAME='San Joaquin', SHORT_NAME='SJQ' WHERE WT_COUNTY_ID = 46;
UPDATE WT_COUNTY SET NAME='San Luis Obispo', SHORT_NAME='SLO' WHERE WT_COUNTY_ID = 47;
UPDATE WT_COUNTY SET NAME='San Mateo', SHORT_NAME='SMT' WHERE WT_COUNTY_ID = 48;
UPDATE WT_COUNTY SET NAME='Solano', SHORT_NAME='SOL' WHERE WT_COUNTY_ID = 49;
UPDATE WT_COUNTY SET NAME='Sonoma', SHORT_NAME='SON' WHERE WT_COUNTY_ID = 50;
UPDATE WT_COUNTY SET NAME='Stanislaus', SHORT_NAME='STA' WHERE WT_COUNTY_ID = 51;
UPDATE WT_COUNTY SET NAME='Sutter', SHORT_NAME='SUT' WHERE WT_COUNTY_ID = 52;
UPDATE WT_COUNTY SET NAME='Tehama', SHORT_NAME='TEH' WHERE WT_COUNTY_ID = 53;
UPDATE WT_COUNTY SET NAME='Trinity', SHORT_NAME='TRI' WHERE WT_COUNTY_ID = 54;
UPDATE WT_COUNTY SET NAME='Tulare', SHORT_NAME='TUL' WHERE WT_COUNTY_ID = 55;
UPDATE WT_COUNTY SET NAME='Tuolumne', SHORT_NAME='TUO' WHERE WT_COUNTY_ID = 56;
UPDATE WT_COUNTY SET NAME='Ventura', SHORT_NAME='VEN' WHERE WT_COUNTY_ID = 57;
UPDATE WT_COUNTY SET NAME='Yolo', SHORT_NAME='YOL' WHERE WT_COUNTY_ID = 58;
UPDATE WT_COUNTY SET NAME='Yuba', SHORT_NAME='YUB' WHERE WT_COUNTY_ID = 59;



