CREATE OR REPLACE VIEW ATTACHMENT_VIEW AS
SELECT WT_ATTACHMENT.WT_ATTACHMENT_ID
,WT_ATTACHMENT.FILENAME
,WT_ATTACHMENT.DESCRIPTION
,WT_ATTACHMENT.CREATED_DATE
,WT_ATTACHMENT.MODIFIED_DATE
,NULL AS FILE_LOB
,WT_ATTACHMENT.MIME_TYPE
,WT_ATTACHMENT.ATTACHMENT_TYPE
,WT_ATTACHMENT.TITLE
,WT_ATTACHMENT.CREATED_BY_ID
,WT_ATTACHMENT.UPDATED_BY_ID
,WT_ATTACHMENT.CEQA_SUBMITTED_DATE
,WT_ATTACHMENT.FILE_SIZE
,WT_ATTACHMENT.IS_ACTIVE
,WT_ATT_CHECKLIST.WT_CHECKLIST_ID
,APP_USER.USER_ID AS APP_USER_USER_ID
,APP_USER.USERNAME AS APP_USER_USERNAME
,APP_USER.PASSWORD AS APP_USER_PASSWORD
,APP_USER.ACTIVE AS APP_USER_ACTIVE
,APP_USER.CREATED_DATE AS APP_USER_CREATED_DATE
,APP_USER.UPDATED_DATE AS APP_USER_UPDATED_DATE
,APP_USER.WT_CONTACT_ID AS APP_USER_WT_CONTACT_ID
,APP_USER.NEED_PASSWORD_RESET AS APP_USER_NEED_PASSWORD_RESET
,WT_CONTACT.WT_CONTACT_ID AS WT_CONTACT_WT_CONTACT_ID
,WT_CONTACT.WT_AGENCY_ID AS WT_CONTACT_WT_AGENCY_ID
,WT_CONTACT.TITLE AS WT_CONTACT_TITLE
,WT_CONTACT.LAST_NAME AS WT_CONTACT_LAST_NAME
,WT_CONTACT.MIDDLE_NAME AS WT_CONTACT_MIDDLE_NAME
,WT_CONTACT.FIRST_NAME AS WT_CONTACT_FIRST_NAME
,WT_CONTACT.EMAIL AS WT_CONTACT_EMAIL
,WT_CONTACT.PHONE_TYPE AS WT_CONTACT_PHONE_TYPE
,WT_CONTACT.PHONE_NUMBER AS WT_CONTACT_PHONE_NUMBER
,WT_CONTACT.ADDRESS1 AS WT_CONTACT_ADDRESS1
,WT_CONTACT.ADDRESS2 AS WT_CONTACT_ADDRESS2
,WT_CONTACT.WT_CITY_ID AS WT_CONTACT_WT_CITY_ID
,WT_CONTACT.WT_STATE_ID AS WT_CONTACT_WT_STATE_ID
,WT_CONTACT.ZIPCODE AS WT_CONTACT_ZIPCODE
,WT_CONTACT.CREATED_DATE AS WT_CONTACT_CREATED_DATE
,WT_CONTACT.CREATED_BY_ID AS WT_CONTACT_CREATED_BY_ID
,WT_CONTACT.UPDATED_BY_ID AS WT_CONTACT_UPDATED_BY_ID
,WT_CONTACT.UPDATED_DATE AS WT_CONTACT_UPDATED_DATE
,WT_CONTACT.IS_ACTIVE AS WT_CONTACT_IS_ACTIVE
,WT_CONTACT.CITY_NAME AS WT_CONTACT_CITY_NAME
,WT_CONTACT.IS_BUYERS_CONTACT AS WT_CONTACT_IS_BUYERS_CONTACT
FROM WT_ATTACHMENT
LEFT JOIN WT_ATT_CHECKLIST ON WT_ATTACHMENT.WT_ATTACHMENT_ID = WT_ATT_CHECKLIST.WT_ATTACHMENT_ID JOIN APP_USER
JOIN WT_CONTACT ON APP_USER.WT_CONTACT_ID = WT_CONTACT.WT_CONTACT_ID ON WT_ATTACHMENT.CREATED_BY_ID = APP_USER.USER_ID;