--------------------------------------------------------------------------------
--  DROP ALL TABLES AND SEQUENCE AND TRIGGERS
--------------------------------------------------------------------------------
DROP TRIGGER WT_ATTACHMENT_UPDATETRIG;
DROP TRIGGER WT_ATTACHMENT_PKTRIG;
DROP SEQUENCE WT_ATTACHMENT_PKSEQ;
DROP TABLE WT_TRANS_ATTACHMENTS;
DROP TABLE WT_ATTACHMENT;

--------------------------------------------------------------------------------
--  DDL for Table WT_ATTACHMENT
--------------------------------------------------------------------------------
CREATE TABLE WT_ATTACHMENT (
  WT_ATTACHMENT_ID NUMERIC(16,0) PRIMARY KEY
  ,FILENAME VARCHAR(128)
  ,DESCRIPTION VARCHAR(256)
  ,CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
  ,MODIFIED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
  ,FILE_LOB BLOB
  ,MIME_TYPE VARCHAR(64)
);
/
CREATE SEQUENCE WT_ATTACHMENT_PKSEQ START WITH 1;
/
CREATE TRIGGER WT_ATTACHMENT_PKTRIG 
BEFORE INSERT 
ON WT_ATTACHMENT
FOR EACH ROW 
BEGIN 
  IF :NEW.WT_ATTACHMENT_ID IS NULL THEN
    SELECT WT_ATTACHMENT_PKSEQ.NEXTVAL 
    INTO :NEW.WT_ATTACHMENT_ID
    FROM DUAL;
  END IF;  
END WT_ATTACHMENT_PKTRIG;
/
CREATE TRIGGER WT_ATTACHMENT_UPDATETRIG 
BEFORE UPDATE
ON WT_ATTACHMENT
FOR EACH ROW 
BEGIN 
  IF :NEW.MODIFIED_DATE IS NULL THEN
    SELECT SYSTIMESTAMP
    INTO :NEW.MODIFIED_DATE
    FROM DUAL;
  END IF;  
END WT_ATTACHMENT_UPDATETRIG;
/

--------------------------------------------------------------------------------
--  DDL for Table WT_TRANS_ATTACHMENT
--------------------------------------------------------------------------------
CREATE TABLE WT_TRANS_ATTACHMENTS (
  WT_TRANS_ID REFERENCES WT_TRANS(WT_TRANS_ID)
  ,WT_ATTACHMENT_ID REFERENCES WT_ATTACHMENT(WT_ATTACHMENT_ID) ON DELETE CASCADE
  ,UNIQUE(WT_TRANS_ID,WT_ATTACHMENT_ID)
);
/















