--------------------------------------------------------------------------------
--  DROP ALL TABLES AND SEQUENCE
--------------------------------------------------------------------------------
DROP TRIGGER WT_CONTACT_PHONE_PKTRIG;
DROP SEQUENCE WT_CONTACT_PHONE_PKSEQ;
DROP TABLE WT_CONTACT_PHONE;

DROP TRIGGER WT_CONTACT_PKTRIG;
DROP SEQUENCE WT_CONTACT_PKSEQ;
DROP TABLE WT_CONTACT;


--------------------------------------------------------------------------------
--  DDL for Table WT_CONTACT
--------------------------------------------------------------------------------
CREATE TABLE WT_CONTACT (
  WT_CONTACT_ID NUMERIC(16,0) PRIMARY KEY
  ,USER_ID REFERENCES APP_USER(USER_ID)
  ,WT_AGENCY_ID REFERENCES WT_AGENCY(WT_AGENCY_ID)
  ,TITLE VARCHAR2(32)
  ,LAST_NAME VARCHAR2(32)
  ,MIDDLE_NAME VARCHAR2(32)
  ,FIRST_NAME VARCHAR2(32)
  ,EMAIL VARCHAR2(64)
  ,CREATE_DATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);
/

CREATE SEQUENCE WT_CONTACT_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_CONTACT_PKTRIG
BEFORE INSERT
ON WT_CONTACT
FOR EACH ROW
BEGIN
  IF :NEW.WT_CONTACT_ID IS NULL THEN
    SELECT WT_CONTACT_PKSEQ.NEXTVAL
    INTO :NEW.WT_CONTACT_ID
    FROM DUAL;
  END IF;
END WT_CONTACT;
/

--------------------------------------------------------------------------------
--  DDL for Table WT_CONTACT_PHONE
--------------------------------------------------------------------------------
CREATE TABLE WT_CONTACT_PHONE (
  WT_CONTACT_PHONE_ID NUMERIC(16,0) PRIMARY KEY
  ,WT_CONTACT_ID REFERENCES WT_CONTACT(WT_CONTACT_ID)
  ,PHONE_TYPE VARCHAR2(32)
  ,PHONE_NUMBER VARCHAR2(20)
  ,PHONE_EXTENSION VARCHAR2(5)
);
/

CREATE SEQUENCE WT_CONTACT_PHONE_PKSEQ  
  START WITH 1
  INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER WT_CONTACT_PHONE_PKTRIG
BEFORE INSERT
ON WT_CONTACT_PHONE
FOR EACH ROW
BEGIN
  IF :NEW.WT_CONTACT_PHONE_ID IS NULL THEN
    SELECT WT_CONTACT_PHONE_PKSEQ.NEXTVAL
    INTO :NEW.WT_CONTACT_PHONE_ID
    FROM DUAL;
  END IF;
END WT_CONTACT_PHONE;
/
