--------------------------------------------------------------------------------
--  DROP ALL TABLES AND SEQUENCE
--------------------------------------------------------------------------------

DROP TRIGGER WT_TRANS_PKTRIG;
DROP SEQUENCE WT_TRANS_PKSEQ;
DROP TABLE WT_TRANS;

DROP TABLE WT_AGENCY;

--------------------------------------------------------------------------------
--  DDL for Table WT_HEAD
--------------------------------------------------------------------------------
CREATE TABLE WT_AGENCY (
  WT_AGENCY_ID VARCHAR2(16) PRIMARY KEY
  ,WT_FULL_NAME VARCHAR2(128) 
  ,WT_ACTIVE_IND VARCHAR2(1) DEFAULT 'Y'
);
/

--------------------------------------------------------------------------------
--  DDL for Table WT_TRANS
--------------------------------------------------------------------------------
CREATE TABLE WT_TRANS (
  WT_TRANS_ID NUMERIC PRIMARY KEY
  ,WT_TRANS_NUM VARCHAR2(32) NOT NULL
  ,TRANS_YEAR VARCHAR2(4) NOT NULL
  ,WT_AGENCY_ID REFERENCES WT_AGENCY(WT_AGENCY_ID) 
  ,PRO_TRANS_QUA VARCHAR2(16)
  ,ACT_TRANS_QUA VARCHAR2(16)
  ,DWR_PRO_APPR_DATE DATE
  ,TRANS_WIN_START DATE
  ,TRANS_WIN_END DATE
  ,PRO_AGREE_PAID NUMBER(18,2)
  ,ACT_AMT_PAID NUMBER(18,2)
  ,CAL_AMT_PAID NUMBER(18,2)
  ,PRO_UNIT_COST NUMBER(18,2)
  ,CAL_UNIT_COST NUMBER(18,2)
  ,FU_TYPE_SWP VARCHAR2(1) DEFAULT 'N' NOT NULL
  ,FU_TYPE_CVP VARCHAR2(1) DEFAULT 'N' NOT NULL
  ,FU_TYPE_OTHER VARCHAR2(1) DEFAULT 'N' NOT NULL
  ,PRO_ACR_IDLE VARCHAR2(8)
  ,PRO_ACR_IDLE_IND VARCHAR2(1) DEFAULT 'N' NOT NULL
  ,ACT_FALL_ACR VARCHAR2(8)
  ,ACT_FALL_ACR_IND VARCHAR2(1) DEFAULT 'N' NOT NULL 
  ,RES_RE_OP VARCHAR2(1) DEFAULT 'N' NOT NULL 
  ,CONS_WATER VARCHAR2(1) DEFAULT 'N' NOT NULL
  ,WELL_USE_NUM VARCHAR2(8)
  ,WELL_USE_NUM_IND VARCHAR2(1) DEFAULT 'N' NOT NULL
  ,WT_COMM VARCHAR2(250)  
  ,UNIQUE(WT_TRANS_NUM)
);
/

CREATE SEQUENCE WT_TRANS_PKSEQ  
  START WITH 1
  INCREMENT BY 1
  CACHE 99999999;
/

CREATE OR REPLACE TRIGGER WT_TRANS_PKTRIG
BEFORE INSERT
ON WT_TRANS
FOR EACH ROW
BEGIN
    SELECT WT_TRANS_PKSEQ.NEXTVAL
    INTO :NEW.WT_TRANS_ID
    FROM DUAL;
END WT_TRANS;
/




